import type { Tool, ToolInput, ToolOutput } from '../types/tool.js';

const ok = (data: unknown): ToolOutput => ({ success: true, data });
const fail = (error: string): ToolOutput => ({ success: false, error });
const num = (v: unknown, fallback = 0) => Number.isFinite(Number(v)) ? Number(v) : fallback;

export const salesFunnelTool: Tool = { id: 'sales-funnel-analysis', name: 'Sales Funnel Analyzer', description: 'Calculate funnel conversion, revenue, bottlenecks and required pipeline volume.', category: 'sales', async execute(input: ToolInput) { const leads=num(input.leads), qualified=num(input.qualified), meetings=num(input.meetings), proposals=num(input.proposals), won=num(input.won), avgDeal=num(input.avgDealValue); if ([leads,qualified,meetings,proposals,won,avgDeal].some(v=>v<0)) return fail('Funnel values cannot be negative.'); return ok({ stages:{leads,qualified,meetings,proposals,won}, conversion:{leadToQualified:leads?qualified/leads:0,qualifiedToMeeting:qualified?meetings/qualified:0,meetingToProposal:meetings?proposals/meetings:0,proposalToWon:proposals?won/proposals:0,overall:leads?won/leads:0}, revenue:won*avgDeal, bottleneck: qualified&&meetings/qualified<0.3?'qualified_to_meeting':meetings&&proposals/meetings<0.3?'meeting_to_proposal':proposals&&won/proposals<0.2?'proposal_to_won':'top_of_funnel' }); } };

export const pipelineForecastTool: Tool = { id:'pipeline-forecast', name:'Pipeline Forecast', description:'Forecast weighted pipeline revenue and identify the amount needed to hit a revenue target.', category:'sales', async execute(input: ToolInput) { const target=num(input.targetRevenue), pipeline=num(input.pipelineValue), probability=Math.min(1,Math.max(0,num(input.winRate,0.2))); const weighted=pipeline*probability; return ok({targetRevenue:target,pipelineValue:pipeline,winRate:probability,weightedPipeline:weighted,gapToTarget:Math.max(0,target-weighted),requiredPipeline:probability?target/probability:0}); } };

export const offerRoiTool: Tool = { id:'offer-roi-calculator', name:'Offer ROI Calculator', description:'Model client ROI, break-even and maximum acquisition cost for a marketing offer.', category:'sales', async execute(input: ToolInput) { const leads=num(input.leads), closeRate=Math.max(0,num(input.closeRate)), dealValue=num(input.dealValue), grossMargin=Math.max(0,Math.min(1,num(input.grossMargin,1))), spend=num(input.adSpend), serviceFee=num(input.serviceFee); const customers=leads*closeRate, revenue=customers*dealValue, grossProfit=revenue*grossMargin-serviceFee-spend; return ok({customers,revenue,grossProfit,roi:serviceFee+spend?grossProfit/(serviceFee+spend):0,breakEvenCustomers:dealValue*grossMargin?(serviceFee+spend)/(dealValue*grossMargin):0,maxAcquisitionCost:dealValue*grossMargin}); } };

export const followupPlannerTool: Tool = { id:'followup-planner', name:'Follow-up Planner', description:'Generate a prioritized follow-up plan from lead age, score and engagement.', category:'sales', async execute(input: ToolInput) { const leads=Array.isArray(input.leads)?input.leads:[]; const ranked=leads.map((lead:any,i:number)=>({lead,index:i,priority:Math.min(100,Math.round(num(lead.score)*0.65+num(lead.engagement)*0.25+Math.max(0,Math.min(10,num(lead.daysSinceContact)))))})).sort((a,b)=>b.priority-a.priority); return ok({count:ranked.length,items:ranked.map(x=>({...x,nextAction:x.priority>=75?'follow_up_now':x.priority>=50?'follow_up_soon':'nurture'}))}); } };

export const growthTools: Tool[]=[salesFunnelTool,pipelineForecastTool,offerRoiTool,followupPlannerTool];
