'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import DashboardLayout from '@/components/dashboard/DashboardLayout';

type V=string|boolean|number;
const defaults:Record<string,V>={founder_name:'Dev',workspace_name:'NexorAIOS',founder_role:'Founder · Nexor',avatar_url:'/founder-avatar.svg',show_avatar:true,theme:'Executive Pearl',accent:'Indigo',density:'Comfortable',clock_24h:false,timezone_mode:'Browser',account_timezone:'Asia/Kolkata',language:'English',master_autopilot:true,outbound_enabled:true,campaign_discovery:true,whatsapp_generation:true,whatsapp_sending:true,followups:true,outreach:true,social_publishing:true,daily_reports:true,growth_reports:true,quiet_hours:true,quiet_start:21,quiet_end:9,daily_send_limit:100,approval_mode:'Autonomous eligible',realtime_refresh:true,refresh_seconds:30};
const groups=[
 ['PROFILE & IDENTITY',['founder_name','workspace_name','founder_role','avatar_url','show_avatar']],
 ['APPEARANCE',['theme','accent','density','clock_24h']],
 ['TIME & LANGUAGE',['timezone_mode','account_timezone','language']],
 ['AUTOPILOT & OUTBOUND',['master_autopilot','outbound_enabled','campaign_discovery','whatsapp_generation','whatsapp_sending','followups','outreach','social_publishing','daily_reports','growth_reports']],
 ['OUTREACH POLICY',['approval_mode','quiet_hours','quiet_start','quiet_end','daily_send_limit']],
 ['LIVE DASHBOARD',['realtime_refresh','refresh_seconds']],
] as const;
const meta:Record<string,{label:string;description:string;type:'toggle'|'select'|'text'|'number';options?:string[]}>= {
 founder_name:{label:'Founder display name',description:'Shown across the executive workspace.',type:'text'},workspace_name:{label:'Workspace name',description:'Primary operating-system label.',type:'text'},founder_role:{label:'Founder role',description:'Identity subtitle in navigation.',type:'text'},avatar_url:{label:'Founder photo URL',description:'Use a hosted image URL when available.',type:'text'},show_avatar:{label:'Show founder photo',description:'Display the founder image in command surfaces.',type:'toggle'},
 theme:{label:'Theme',description:'Executive visual system.',type:'select',options:['Executive Pearl','Obsidian','Light','Gold Executive','System']},accent:{label:'Accent',description:'Primary interaction accent.',type:'select',options:['Indigo','Violet','Cyan','Emerald','Gold','Monochrome']},density:{label:'Interface density',description:'Operational information density.',type:'select',options:['Comfortable','Compact','Dense','Terminal']},clock_24h:{label:'24-hour clock',description:'Use 24-hour timestamps.',type:'toggle'},timezone_mode:{label:'Timezone source',description:'Timezone used by the workspace.',type:'select',options:['Browser','Account','UTC']},account_timezone:{label:'Account timezone',description:'Fallback timezone.',type:'select',options:['Asia/Kolkata','Asia/Dubai','Europe/London','America/New_York','America/Los_Angeles','UTC']},language:{label:'Interface language',description:'Dashboard language preference.',type:'select',options:['English','Hindi','Hinglish']},
 master_autopilot:{label:'Master Autopilot',description:'Global autonomous operating loop.',type:'toggle'},outbound_enabled:{label:'Outbound communications',description:'Allow eligible outbound workers.',type:'toggle'},campaign_discovery:{label:'Automatic lead discovery',description:'Run scheduled lead discovery.',type:'toggle'},whatsapp_generation:{label:'WhatsApp generation',description:'Generate personalized drafts.',type:'toggle'},whatsapp_sending:{label:'WhatsApp sending',description:'Allow eligible WhatsApp jobs to send.',type:'toggle'},followups:{label:'Automatic follow-ups',description:'Process due follow-ups.',type:'toggle'},outreach:{label:'Automatic outreach queue',description:'Process the outbound queue.',type:'toggle'},social_publishing:{label:'Social publishing',description:'Allow connected social workers.',type:'toggle'},daily_reports:{label:'Daily reports',description:'Generate owner reports.',type:'toggle'},growth_reports:{label:'Growth reports',description:'Generate recurring growth summaries.',type:'toggle'},
 approval_mode:{label:'Approval policy',description:'Control how outbound is released.',type:'select',options:['Autonomous eligible','Always approve','Never send']},quiet_hours:{label:'Quiet hours',description:'Block commercial sends during local quiet hours.',type:'toggle'},quiet_start:{label:'Quiet hours start',description:'Local hour.',type:'number'},quiet_end:{label:'Quiet hours end',description:'Local hour.',type:'number'},daily_send_limit:{label:'Daily outbound limit',description:'Maximum automated attempts per day.',type:'number'},realtime_refresh:{label:'Realtime dashboard refresh',description:'Refresh operational data without reload.',type:'toggle'},refresh_seconds:{label:'Refresh interval',description:'Seconds between lightweight refreshes.',type:'number'}
};
const serverKeys=new Set(['master_autopilot','outbound_enabled','campaign_discovery','whatsapp_generation','whatsapp_sending','followups','outreach','social_publishing','daily_reports','growth_reports']);

export default function SettingsStudio(){
 const [values,setValues]=useState<Record<string,V>>(defaults); const [query,setQuery]=useState(''); const [saved,setSaved]=useState(false); const [status,setStatus]=useState(''); const [clock,setClock]=useState(''); const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const raw=localStorage.getItem('nexor-settings-v3');if(raw)setValues(v=>({...v,...JSON.parse(raw)}));}catch{};const tick=()=>{const d=new Date();setClock(d.toLocaleString([], {weekday:'short',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}))};tick();const id=window.setInterval(tick,1000);return()=>clearInterval(id)},[]);
 useEffect(()=>{fetch('/api/automation/settings',{cache:'no-store'}).then(r=>r.json()).then(x=>{if(Array.isArray(x?.settings))setValues(v=>({...v,...Object.fromEntries(x.settings.map((s:any)=>[s.key,Boolean(s.enabled)]))}))}).catch(()=>{})},[]);
 const visible=useMemo(()=>groups.map(([title,keys])=>({title,keys:keys.filter(k=>{const m=meta[k];return !query||`${title} ${m.label} ${m.description}`.toLowerCase().includes(query.toLowerCase())})})).filter(g=>g.keys.length),[query]);
 const update=(key:string,value:V)=>{setValues(v=>({...v,[key]:value}));setSaved(false);setStatus('Unsaved changes')};
 const upload=(file:File)=>{if(!file.type.startsWith('image/'))return; if(file.size>2_000_000){setStatus('Photo must be under 2 MB');return;} const reader=new FileReader();reader.onload=()=>{update('avatar_url',String(reader.result));setStatus('Photo staged locally — save changes to keep it on this browser')};reader.readAsDataURL(file)};
 const save=async()=>{localStorage.setItem('nexor-settings-v3',JSON.stringify(values));const settings=[...serverKeys].filter(k=>typeof values[k]==='boolean').map(key=>({key,enabled:Boolean(values[key])}));try{const r=await fetch('/api/automation/settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({settings})});const x=await r.json();if(!r.ok)throw new Error(x?.error||'Automation settings failed');setSaved(true);setStatus('Saved to Nexor + browser');setTimeout(()=>setSaved(false),1800)}catch(e){setSaved(true);setStatus(`Saved locally. Server automation settings unavailable: ${e instanceof Error?e.message:'unknown error'}`)}};
 const reset=()=>{setValues(defaults);localStorage.setItem('nexor-settings-v3',JSON.stringify(defaults));setStatus('Reset to defaults')};
 return <DashboardLayout><main className="min-h-full space-y-4 pb-10">
  <section className="nexor-panel overflow-hidden"><div className="flex flex-col gap-5 p-5 md:p-7 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-4"><div className="relative h-16 w-16 shrink-0 overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface-2)]"><img src={String(values.avatar_url)} alt="Founder" className="h-full w-full object-cover" onError={e=>{e.currentTarget.src='/founder-avatar.svg'}}/><button onClick={()=>fileRef.current?.click()} className="absolute inset-x-1 bottom-1 rounded-lg bg-black/65 px-2 py-1 text-[7px] font-bold text-white">CHANGE PHOTO</button><input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/></div><div><div className="font-mono text-[8px] tracking-[.22em] text-[var(--accent)]">NEXORAIOS · ADMIN CONTROL PLANE</div><h1 className="mt-1 text-2xl font-semibold tracking-[-.04em] md:text-3xl">Settings Studio</h1><p className="mt-1 text-[9px] leading-4 text-[var(--text-secondary)]">Real controls for appearance, identity and autonomous operations — not decorative switches.</p></div></div><div className="flex flex-wrap gap-2 text-[8px] font-mono"><span className="rounded-full border border-[var(--success)]/25 bg-[var(--success)]/10 px-3 py-2 text-[var(--success)]">● LIVE</span><span className="rounded-full border border-[var(--border)] px-3 py-2 text-[var(--text-muted)]">{clock||'—'}</span></div></div><div className="grid gap-3 border-t border-[var(--border)] p-4 sm:grid-cols-[1fr_auto]"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search settings…" className="h-11 rounded-xl border border-[var(--border)] bg-[var(--surface-2)] px-4 text-[11px] outline-none focus:border-[var(--primary)]"/><div className="flex gap-2"><button onClick={save} className="rounded-xl bg-[var(--primary)] px-5 py-2.5 text-[9px] font-bold text-white">{saved?'SAVED ✓':'SAVE CHANGES'}</button><button onClick={reset} className="rounded-xl border border-[var(--border)] px-4 py-2.5 text-[9px]">RESET</button></div></div>{status&&<div className="border-t border-[var(--border)] px-4 py-3 text-[8px] text-[var(--text-muted)]">{status}</div>}</section>
  <section className="grid gap-4 lg:grid-cols-[220px_1fr]"><aside className="nexor-panel h-fit p-3 lg:sticky lg:top-4"><div className="px-3 py-2 font-mono text-[7px] tracking-[.18em] text-[var(--text-muted)]">CONTROL INDEX</div>{groups.map(([title])=><a key={title} href={`#${title.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}`} className="block rounded-lg px-3 py-2 text-[8px] text-[var(--text-secondary)] hover:bg-[var(--surface-2)]">{title}</a>)}</aside><div className="space-y-4">{visible.map(g=><section key={g.title} id={g.title.replace(/[^a-z0-9]+/gi,'-').toLowerCase()} className="nexor-panel overflow-hidden"><div className="border-b border-[var(--border)] px-5 py-4"><div className="font-mono text-[7px] tracking-[.18em] text-[var(--accent)]">{g.title}</div><div className="mt-1 text-[12px] font-semibold">Operational controls</div></div><div className="divide-y divide-[var(--border)]">{g.keys.map(key=>{const m=meta[key];const val=values[key];return <div key={key} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0 sm:max-w-[65%]"><div className="text-[10px] font-semibold">{m.label}</div><div className="mt-1 text-[8px] leading-4 text-[var(--text-muted)]">{m.description}</div></div><div className="w-full sm:w-auto">{m.type==='toggle'?<button onClick={()=>update(key,!Boolean(val))} className={`relative h-7 w-12 rounded-full ${Boolean(val)?'bg-[var(--primary)]':'bg-[var(--surface-3)]'}`} aria-label={m.label}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition-all ${Boolean(val)?'left-6':'left-1'}`}/></button>:m.type==='select'?<select value={String(val)} onChange={e=>update(key,e.target.value)} className="h-9 min-w-[170px] rounded-lg border border-[var(--border)] bg-[var(--surface-2)] px-3 text-[9px]">{m.options?.map(o=><option key={o}>{o}</option>)}</select>:<input type={m.type==='number'?'number':'text'} value={String(val??'')} onChange={e=>update(key,m.type==='number'?Number(e.target.value):e.target.value)} className="h-9 w-full rounded-lg border border-[var(--border)] bg-[var(--surface-2)] px-3 text-[9px] sm:w-[220px]"/>}</div></div>})}</div></section>)}</div></section>
  <section className="nexor-panel grid gap-3 p-5 sm:grid-cols-3"><div><div className="font-mono text-[7px] text-[var(--text-muted)]">AUTOPILOT</div><div className="mt-1 text-[11px] font-semibold">{values.master_autopilot?'ENABLED':'PAUSED'}</div></div><div><div className="font-mono text-[7px] text-[var(--text-muted)]">OUTBOUND</div><div className="mt-1 text-[11px] font-semibold">{values.outbound_enabled?'ENABLED':'PAUSED'}</div></div><div><div className="font-mono text-[7px] text-[var(--text-muted)]">AUTOMATION CONTROL</div><Link href="/dashboard/settings/automation" className="mt-1 inline-block text-[8px] text-[var(--accent)]">Open detailed automation →</Link></div></section>
 </main></DashboardLayout>;
}
