'use client';
import {useEffect,useRef,useState} from 'react';
import DashboardLayout from '@/components/dashboard/DashboardLayout';
const automation=[['master_autopilot','Master Autopilot'],['outbound_enabled','Outbound communications'],['campaign_discovery','Automatic lead discovery'],['whatsapp_generation','WhatsApp generation'],['whatsapp_sending','WhatsApp sending'],['followups','Automatic follow-ups'],['outreach','Automatic outreach queue'],['social_publishing','Social publishing'],['daily_reports','Daily reports'],['growth_reports','Growth reports']];
const defaults={theme:'Executive Pearl',accent:'Indigo',density:'Comfortable',font_scale:'Default',founder_name:'Dev',founder_role:'Founder · Nexor',avatar_url:'/founder-avatar.svg'};
export default function SettingsStudio(){const[values,setValues]=useState<any>(defaults);const[server,setServer]=useState<Record<string,boolean>>({});const[status,setStatus]=useState('');const[file,setFile]=useState<File|null>(null);const[busy,setBusy]=useState('');const ref=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const a=JSON.parse(localStorage.getItem('nexor-settings-v2')||'{}');setValues({...defaults,...a})}catch{};fetch('/api/automations/settings',{cache:'no-store'}).then(r=>r.json()).then(x=>{if(Array.isArray(x?.settings))setServer(Object.fromEntries(x.settings.map((s:any)=>[s.key,Boolean(s.enabled)])))}).catch(()=>{})},[]);
 const update=(k:string,v:any)=>setValues((x:any)=>({...x,[k]:v}));
 const save=async()=>{setStatus('Saving…');try{localStorage.setItem('nexor-settings-v2',JSON.stringify(values));for(const[key]=[] of [] as any[]){};for(const[key,label] of automation){if(typeof server[key]==='boolean'&&server[key]!==undefined){const r=await fetch('/api/automations/settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({key,enabled:server[key]})});if(!r.ok)throw new Error(`Could not save ${label}`)}}window.dispatchEvent(new Event('nexor-settings-updated'));setStatus('Saved · automation controls persisted to production database')}catch(e){setStatus(e instanceof Error?e.message:String(e))}};
 const upload=(f:File)=>{if(!f.type.startsWith('image/'))return setStatus('Choose an image file');if(f.size>2_000_000)return setStatus('Photo must be under 2 MB');setFile(f);const r=new FileReader();r.onload=()=>update('avatar_url',String(r.result));r.readAsDataURL(f)};
 return <DashboardLayout><main className="mx-auto w-full max-w-6xl space-y-4 sm:space-y-5"><section className="nexor-panel p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><button onClick={()=>ref.current?.click()} className="relative h-16 w-16 overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface-2)]"><img src={values.avatar_url} alt="Founder" className="h-full w-full object-cover" onError={e=>{e.currentTarget.src='/founder-avatar.svg'}}/><span className="absolute inset-x-1 bottom-1 rounded bg-black/65 py-1 text-[7px] font-bold text-white">UPLOAD</span></button><input ref={ref} type="file" accept="image/*" hidden onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/><div><div className="font-mono text-[7px] tracking-[.2em] text-[var(--accent)]">NEXORAIOS · SETTINGS STUDIO</div><h1 className="mt-1 text-2xl font-semibold">Control everything from here</h1><p className="mt-1.5 text-[9px] leading-5 text-[var(--text-secondary)]">Appearance, identity and real production automation switches — no decorative controls.</p></div></div><div className="rounded-xl bg-[var(--surface-2)] px-4 py-3 text-[8px] text-[var(--text-muted)]">{status||'Changes are local for appearance and persistent in the automation database.'}</div></div></section>
 <section className="grid gap-4 lg:grid-cols-2"><div className="nexor-panel p-5"><div className="text-[12px] font-semibold">Appearance</div><p className="mt-1 text-[8px] text-[var(--text-muted)]">Changes apply across the OS immediately after Save.</p><div className="mt-4 grid gap-3"><label className="text-[8px] font-mono text-[var(--text-muted)]">THEME<select value={values.theme} onChange={e=>update('theme',e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-[var(--border)] bg-[var(--surface-2)] px-3 text-[10px]"><option>Executive Pearl</option><option>Obsidian</option><option>Light</option><option>Gold Executive</option></select></label><label className="text-[8px] font-mono text-[var(--text-muted)]">ACCENT<select value={values.accent} onChange={e=>update('accent',e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-[var(--border)] bg-[var(--surface-2)] px-3 text-[10px]">{['Indigo','Violet','Cyan','Emerald','Gold','Monochrome'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-[8px] font-mono text-[var(--text-muted)]">FONT SIZE<select value={values.font_scale} onChange={e=>update('font_scale',e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-[var(--border)] bg-[var(--surface-2)] px-3 text-[10px]"><option>Small</option><option>Default</option><option>Large</option><option>XL</option></select></label><label className="text-[8px] font-mono text-[var(--text-muted)]">DENSITY<select value={values.density} onChange={e=>update('density',e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-[var(--border)] bg-[var(--surface-2)] px-3 text-[10px]"><option>Comfortable</option><option>Compact</option><option>Dense</option><option>Terminal</option></select></label></div></div>
 <div className="nexor-panel overflow-hidden"><div className="p-5"><div className="text-[12px] font-semibold">Autopilot & outbound</div><p className="mt-1 text-[8px] text-[var(--text-muted)]">These switches write to the production automation settings.</p></div><div className="divide-y divide-[var(--border)]">{automation.map(([key,label])=><div key={key} className="flex items-center gap-4 px-5 py-3.5"><div className="min-w-0 flex-1"><div className="text-[10px] font-semibold">{label}</div><div className="mt-0.5 font-mono text-[7px] text-[var(--text-muted)]">{server[key]?'ENABLED':'PAUSED'}</div></div><button disabled={busy===key} onClick={()=>{setBusy(key);setServer(x=>({...x,[key]:!x[key]}));setBusy('')}} className={`relative h-7 w-12 rounded-full ${server[key]?'bg-[var(--primary)]':'bg-[var(--surface-3)]'}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${server[key]?'left-6':'left-1'}`}/></button></div>)}</div></div></section>
 <section className="nexor-panel p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-[12px] font-semibold">Identity</div><div className="mt-1 text-[8px] text-[var(--text-muted)]">Your uploaded photo and founder name appear in the navigation.</div></div><div className="flex gap-2"><input value={values.founder_name} onChange={e=>update('founder_name',e.target.value)} className="h-10 w-36 rounded-lg border border-[var(--border)] bg-[var(--surface-2)] px-3 text-[9px]"/><button onClick={save} className="rounded-lg bg-[var(--primary)] px-5 py-2.5 text-[9px] font-bold text-white">SAVE ALL</button></div></div></section>
 </main></DashboardLayout>}
