'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import DashboardLayout from '@/components/dashboard/DashboardLayout';

type Overview = {
  generatedAt: string;
  today: { totalLeads:number; qualified:number; outreachReady:number; replied:number; positiveReplies:number; meetings:number; proposals:number; won:number; revenue:string; emailsSent:number; whatsappSent:number; followups:number; failedJobs:number; runningCampaigns:number };
  pipeline: {open:number; qualified:number; proposal:number; won:number; lost:number};
  hotLeads:Array<{id:string;business_name:string;country:string;niche:string;audit_score:number;status:string}>;
  activity:Array<{id:string;type:string;message:string;created_at:string}>;
  integrations:Record<string,string>;
  automation:Array<{key:string;label:string;enabled:boolean;updatedAt:string|null}>;
  autopilot:{enabled:boolean};
};

const labels:Record<string,string>={campaign_discovery:'Lead Discovery',scheduler:'Automation Scheduler',job_autopilot:'Job Autopilot',autopilot:'Business Autopilot',whatsapp_generation:'WhatsApp Generation',whatsapp_sending:'WhatsApp Sending',followups:'Follow-ups',outreach:'Outreach Queue',social_publishing:'Social Publishing',daily_reports:'Daily Reports'};
function formatNumber(v:number){return new Intl.NumberFormat('en-IN').format(v||0)}
function greeting(hour:number){if(hour<12)return 'Good morning';if(hour<18)return 'Good afternoon';return 'Good evening'}
function formatClock(d:Date, h24:boolean){return d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:!h24})}

export default function CommandCenter(){
  const [command,setCommand]=useState(''); const [running,setRunning]=useState(false); const [loading,setLoading]=useState(true); const [overview,setOverview]=useState<Overview|null>(null); const [error,setError]=useState(''); const [controlBusy,setControlBusy]=useState<string|null>(null); const [commandResult,setCommandResult]=useState(''); const [now,setNow]=useState(new Date()); const [tz,setTz]=useState('UTC');
  useEffect(()=>{setTz(Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC');const id=window.setInterval(()=>setNow(new Date()),1000);return()=>window.clearInterval(id)},[]);
  async function loadOverview(){try{const r=await fetch('/api/founder/overview',{cache:'no-store'});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'Overview unavailable');setOverview(d);setError('')}catch(e){setError(e instanceof Error?e.message:'Overview unavailable')}finally{setLoading(false)}}
  useEffect(()=>{void loadOverview();const id=window.setInterval(()=>void loadOverview(),15000);return()=>window.clearInterval(id)},[]);
  async function runCommand(q?:string){const query=(q??command).trim();if(!query||running)return;setRunning(true);setCommandResult('');try{const r=await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'Command failed');setCommandResult(d.execution?.success?'Command completed successfully.':'Command returned without success.');await loadOverview()}catch(e){setCommandResult(e instanceof Error?e.message:'Command failed')}finally{setRunning(false)}}
  async function setAutomation(key:string,enabled:boolean){if(controlBusy)return;setControlBusy(key);try{const r=await fetch('/api/automations/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key,enabled})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'Unable to change automation');await loadOverview()}catch(e){setError(e instanceof Error?e.message:'Unable to change automation')}finally{setControlBusy(null)}}
  const stats=useMemo(()=>{const t=overview?.today;return [[formatNumber(t?.totalLeads??0),'LEADS','◉'],[formatNumber(t?.qualified??0),'QUALIFIED','◆'],[formatNumber(t?.outreachReady??0),'OUTREACH READY','↗'],[formatNumber(t?.positiveReplies??0),'POSITIVE REPLIES','✦'],[formatNumber(t?.meetings??0),'MEETINGS','◎'],[formatNumber(t?.whatsappSent??0),'WHATSAPP SENT','◍']]},[overview]);
  const g=greeting(now.getHours());
  return <DashboardLayout><main className="min-h-full pb-8"><div className="mx-auto max-w-[1500px] space-y-5">
    <section className="nexor-panel overflow-hidden">
      <div className="flex flex-col gap-5 p-5 md:p-7 xl:flex-row xl:items-center xl:justify-between">
        <div className="flex items-center gap-4 min-w-0"><div className="relative h-16 w-16 shrink-0 overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface-2)]"><img src="/founder-avatar.svg" alt="Founder" className="h-full w-full object-cover" onError={e=>{e.currentTarget.style.display='none'}}/><span className="absolute inset-0 flex items-center justify-center text-xl font-bold text-[var(--primary)]">D</span></div><div className="min-w-0"><div className="mb-2 flex flex-wrap items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[var(--success)]"/><span className="font-mono text-[7px] font-semibold tracking-[.2em] text-[var(--success)]">FOUNDER COMMAND CENTER · REAL-TIME</span></div><h1 className="text-3xl font-semibold tracking-[-.04em] md:text-4xl">{g}, DEV BOSS.</h1><p className="mt-1.5 text-[10px] text-[var(--text-secondary)]">NexorAIOS is watching the business continuously — not just when you refresh the page.</p></div></div>
        <div className="grid grid-cols-2 gap-2 sm:flex sm:items-center"><div className="rounded-xl border border-[var(--border)] bg-[var(--surface-2)] px-4 py-2.5"><div className="font-mono text-[7px] text-[var(--text-muted)]">LOCAL TIME</div><div className="mt-1 text-[13px] font-semibold">{formatClock(now,false)}</div><div className="mt-0.5 text-[7px] text-[var(--text-muted)]">{tz}</div></div><Link href="/dashboard/settings/studio" className="rounded-xl border border-[var(--primary)]/25 bg-[var(--primary-soft)] px-4 py-3 text-center text-[9px] font-semibold text-[var(--primary)]">ADMIN SETTINGS</Link></div>
      </div>
      <div className="grid grid-cols-2 border-t border-[var(--border)] sm:grid-cols-4"><div className="px-5 py-3"><div className="font-mono text-[7px] text-[var(--text-muted)]">AUTOPILOT</div><div className="mt-1 text-[9px] font-semibold text-[var(--success)]">{overview?.autopilot.enabled?'RUNNING':'PAUSED'}</div></div><div className="border-l border-[var(--border)] px-5 py-3"><div className="font-mono text-[7px] text-[var(--text-muted)]">DATA SYNC</div><div className="mt-1 text-[9px] font-semibold">15s LIVE</div></div><div className="border-t border-[var(--border)] px-5 py-3 sm:border-l sm:border-t-0"><div className="font-mono text-[7px] text-[var(--text-muted)]">GENERATED</div><div className="mt-1 text-[9px] font-semibold">{overview?.generatedAt?new Date(overview.generatedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'—'}</div></div><div className="border-l border-t border-[var(--border)] px-5 py-3 sm:border-t-0"><div className="font-mono text-[7px] text-[var(--text-muted)]">SYSTEM</div><div className="mt-1 text-[9px] font-semibold text-[var(--success)]">{error?'ATTENTION':'OPERATIONAL'}</div></div></div>
    </section>
    {error&&<section className="rounded-xl border border-[var(--warning)]/30 bg-[var(--warning)]/[.06] px-4 py-3 text-[9px] text-[var(--warning)]">Live backend warning: {error}</section>}
    <section className="nexor-panel overflow-hidden"><div className="flex items-center justify-between border-b border-[var(--border)] px-5 py-3.5"><div className="flex items-center gap-2"><span className="text-[var(--primary)]">✦</span><span className="text-[11px] font-semibold">Command Nexor</span></div><span className="font-mono text-[7px] tracking-[.15em] text-[var(--text-muted)]">REAL BACKEND ACTIONS</span></div><div className="p-5"><textarea value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')void runCommand()}} rows={2} placeholder="Tell Nexor what you want done…" className="w-full resize-none bg-transparent text-[15px] leading-7 outline-none placeholder:text-[var(--text-muted)]"/><div className="mt-4 flex flex-col gap-3 border-t border-[var(--border)] pt-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-2">{['Start Nexor','Find leads','Research market','Analyze pipeline'].map(x=><button key={x} onClick={()=>x==='Start Nexor'?void runCommand('start'):setCommand(x)} className="rounded-lg border border-[var(--border)] bg-[var(--surface-2)] px-3 py-2 text-[9px] text-[var(--text-secondary)] hover:text-[var(--text)]">{x}</button>)}</div><button onClick={()=>void runCommand()} disabled={!command.trim()||running} className="rounded-lg bg-[var(--primary)] px-5 py-2.5 text-[9px] font-bold text-white disabled:opacity-40">{running?'RUNNING…':'EXECUTE →'}</button></div>{commandResult&&<div className="mt-3 rounded-lg bg-[var(--surface-2)] px-3 py-2 text-[9px] text-[var(--text-secondary)]">{commandResult}</div>}</div></section>
    <section className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{stats.map(([v,l,i])=><div key={l} className="nexor-panel nexor-panel-hover p-4"><div className="flex items-center justify-between"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-[var(--primary-soft)] text-[var(--primary)]">{i}</span><span className="font-mono text-[7px] text-[var(--text-muted)]">TODAY</span></div><div className="mt-4 text-2xl font-semibold">{loading?'—':v}</div><div className="mt-1 font-mono text-[7px] tracking-[.14em] text-[var(--text-muted)]">{l}</div></div>)}</section>
    <section className="grid gap-4 xl:grid-cols-[1.1fr_.9fr]">
      <div className="nexor-panel"><div className="flex items-center justify-between border-b border-[var(--border)] px-5 py-4"><div><div className="text-[11px] font-semibold">Autonomous Control</div><div className="mt-1 text-[8px] text-[var(--text-muted)]">Every switch is persisted in the automation system.</div></div><Link href="/dashboard/settings/automation" className="text-[8px] text-[var(--primary)]">FULL CONTROL →</Link></div><div className="divide-y divide-[var(--border)]">{(overview?.automation??[]).slice(0,8).map(item=><div key={item.key} className="flex items-center gap-3 px-5 py-3.5"><div className="min-w-0 flex-1"><div className="text-[9px] font-semibold">{labels[item.key]??item.label}</div><div className="mt-0.5 font-mono text-[7px] text-[var(--text-muted)]">{item.enabled?'ACTIVE':'PAUSED'}</div></div><button disabled={controlBusy===item.key} onClick={()=>void setAutomation(item.key,!item.enabled)} className={['relative h-6 w-11 rounded-full transition',item.enabled?'bg-[var(--primary)]':'bg-[var(--surface-3)]'].join(' ')}><span className={['absolute top-1 h-4 w-4 rounded-full bg-white transition',item.enabled?'left-6':'left-1'].join(' ')}/></button></div>)}</div></div>
      <div className="nexor-panel"><div className="border-b border-[var(--border)] px-5 py-4"><div className="text-[11px] font-semibold">Revenue Pipeline</div><div className="mt-1 text-[8px] text-[var(--text-muted)]">Database-backed opportunity stages.</div></div><div className="grid grid-cols-2 gap-3 p-5 md:grid-cols-5">{Object.entries(overview?.pipeline??{open:0,qualified:0,proposal:0,won:0,lost:0}).map(([s,n])=><div key={s} className="rounded-xl border border-[var(--border)] bg-[var(--surface-2)] p-3"><div className="text-lg font-semibold">{formatNumber(n)}</div><div className="mt-1 font-mono text-[7px] uppercase text-[var(--text-muted)]">{s}</div></div>)}</div><div className="grid grid-cols-2 gap-3 border-t border-[var(--border)] px-5 py-4"><div><div className="text-lg font-semibold">{formatNumber(overview?.today.emailsSent??0)}</div><div className="font-mono text-[7px] text-[var(--text-muted)]">EMAIL SENT</div></div><div><div className="text-lg font-semibold">{formatNumber(overview?.today.followups??0)}</div><div className="font-mono text-[7px] text-[var(--text-muted)]">FOLLOW-UPS</div></div></div></div>
    </section>
    <section className="grid gap-4 xl:grid-cols-2"><div className="nexor-panel"><div className="border-b border-[var(--border)] px-5 py-4"><div className="text-[11px] font-semibold">Priority Leads</div><div className="mt-1 text-[8px] text-[var(--text-muted)]">Highest stored audit scores.</div></div><div className="divide-y divide-[var(--border)]">{(overview?.hotLeads??[]).slice(0,6).map(l=><div key={l.id} className="flex items-center gap-3 px-5 py-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-[var(--primary-soft)] font-mono text-[8px] text-[var(--primary)]">{l.audit_score}</div><div className="min-w-0 flex-1"><div className="truncate text-[9px] font-semibold">{l.business_name}</div><div className="mt-0.5 truncate text-[7px] text-[var(--text-muted)]">{l.niche} · {l.country}</div></div><span className="rounded-full bg-[var(--surface-2)] px-2 py-1 font-mono text-[7px]">{l.status}</span></div>)}</div></div><div className="nexor-panel"><div className="border-b border-[var(--border)] px-5 py-4"><div className="text-[11px] font-semibold">Live Activity</div><div className="mt-1 text-[8px] text-[var(--text-muted)]">Latest database events · refreshes every 15 seconds.</div></div><div className="divide-y divide-[var(--border)]">{(overview?.activity??[]).slice(0,7).map(a=><div key={a.id} className="px-5 py-3"><div className="text-[9px] font-medium">{a.message}</div><div className="mt-1 font-mono text-[7px] text-[var(--text-muted)]">{a.type} · {new Date(a.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}</div></div>)}</div></div></section>
    <section className="nexor-panel p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-[11px] font-semibold">Owner Control Plane</div><div className="mt-1 text-[8px] text-[var(--text-muted)]">Theme, appearance, identity, timezone, automation, AI, outreach, social, reporting and developer controls.</div></div><div className="flex gap-2"><Link href="/dashboard/settings/studio" className="rounded-lg bg-[var(--primary)] px-4 py-2.5 text-[9px] font-bold text-white">OPEN SETTINGS STUDIO</Link><Link href="/dashboard/settings/automation" className="rounded-lg border border-[var(--border)] px-4 py-2.5 text-[9px]">AUTOMATION</Link></div></div></section>
  </div></main></DashboardLayout>
}
