'use client';
import Link from 'next/link';
import { useEffect,useMemo,useState } from 'react';
import { nexorTools } from '@/lib/dashboard-tools';

type Data={summary?:Record<string,any>;social?:Record<string,any>;integrations?:Record<string,string>;activity?:any[];hotLeads?:any[];autopilot?:{enabled:boolean};error?:string};
const presets=[['Today',0],['7D',7],['30D',30],['90D',90],['1Y',365]] as const;
function dates(days:number){const to=new Date(),from=new Date();if(days===0)from.setHours(0,0,0,0);else from.setDate(from.getDate()-days);return{from:from.toISOString(),to:to.toISOString()};}
function Stat({label,value}:{label:string;value:any}){return <div className="bg-[var(--surface)] p-4"><div className="nexor-ui-label text-[var(--text-muted)]">{label}</div><div className="mt-2 text-xl font-semibold tabular-nums">{value??0}</div></div>}
function Quick({title,text,href}:{title:string;text:string;href:string}){return <Link href={href} className="rounded-xl border border-[var(--border)] bg-[var(--surface-2)] p-3 hover:border-[var(--primary)]/30"><div className="text-[9px] font-semibold">{title}</div><div className="mt-1 text-[7px] leading-4 text-[var(--text-muted)]">{text}</div></Link>}
export default function FounderCommandCenter(){
 const [preset,setPreset]=useState(0),[from,setFrom]=useState(''),[to,setTo]=useState(''),[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(true);
 const r=useMemo(()=>preset===-1&&from&&to?{from:new Date(`${from}T00:00:00`).toISOString(),to:new Date(`${to}T23:59:59`).toISOString()}:dates(preset),[preset,from,to]);
 const load=async()=>{setLoading(true);try{const res=await fetch(`/api/founder/overview?from=${encodeURIComponent(r.from)}&to=${encodeURIComponent(r.to)}`,{cache:'no-store'});const x=await res.json();if(!res.ok||!x.success)throw new Error(x.error||'Overview unavailable');setData(x);setError('')}catch(e){setError(e instanceof Error?e.message:'Overview unavailable')}finally{setLoading(false)}};
 useEffect(()=>{load()},[r.from,r.to]); useEffect(()=>{if(!refresh)return;const id=window.setInterval(load,30000);return()=>window.clearInterval(id)},[refresh,r.from,r.to]);
 const s=data?.summary||{},so=data?.social||{},ig=data?.integrations||{};const metrics=[['Leads',s.totalLeads],['Qualified',s.qualified],['Messages sent',s.sent],['WhatsApp',s.whatsappSent],['Replies',s.replies],['Meetings',s.meetings],['Won',s.won],['Revenue',s.revenue||'0']];
 return <main className="space-y-5">
 <section className="nexor-panel p-5 sm:p-7"><div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><div className="mb-2 flex flex-wrap gap-2"><span className="rounded-full border border-[var(--accent)]/20 bg-[var(--accent-soft)] px-3 py-1 font-mono text-[7px] font-bold tracking-[.18em] text-[var(--accent)]">NEXOR MEDIA · FOUNDER CONTROL PLANE</span><span className="nexor-live">LIVE TELEMETRY</span></div><h1 className="nexor-ui-title">Everything that matters. One dashboard.</h1><p className="mt-3 max-w-3xl text-[10px] leading-5 text-[var(--text-secondary)]">WhatsApp messaging, social messaging, social posting, CRM, automations, integrations and delivery results measured from production data.</p></div><div className="flex flex-wrap gap-2">{presets.map(([label,days])=><button key={label} onClick={()=>setPreset(days)} className={`rounded-lg border px-3 py-2 font-mono text-[8px] font-bold ${preset===days?'border-[var(--primary)]/30 bg-[var(--primary-soft)] text-[var(--primary)]':'border-[var(--border)] bg-[var(--surface)] text-[var(--text-muted)]'}`}>{label}</button>)}<button onClick={()=>setPreset(-1)} className={`rounded-lg border px-3 py-2 font-mono text-[8px] font-bold ${preset===-1?'border-[var(--primary)]/30 bg-[var(--primary-soft)] text-[var(--primary)]':'border-[var(--border)] bg-[var(--surface)] text-[var(--text-muted)]'}`}>CUSTOM</button></div></div>{preset===-1&&<div className="mt-4 flex flex-wrap gap-2"><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="h-9 rounded-lg border border-[var(--border)] bg-[var(--surface)] px-3 text-[9px]"/><span className="self-center text-[8px] text-[var(--text-muted)]">to</span><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="h-9 rounded-lg border border-[var(--border)] bg-[var(--surface)] px-3 text-[9px]"/></div>}</section>
 {error&&<section className="rounded-xl border border-red-500/20 bg-red-500/[.05] p-4 text-[9px] text-red-500">{error}</section>}
 <section className="grid grid-cols-2 gap-2.5 md:grid-cols-4 xl:grid-cols-8">{metrics.map(([label,value])=><div key={label} className="nexor-panel nexor-panel-hover p-4"><div className="nexor-ui-label text-[var(--text-muted)]">{label}</div><div className="mt-2 nexor-ui-number">{loading?'—':value??0}</div></div>)}</section>
 <section className="grid gap-4 xl:grid-cols-3"><div className="nexor-panel overflow-hidden xl:col-span-2"><div className="nx-section-head"><div><div className="text-[11px] font-semibold">Messaging Control</div><div className="mt-1 text-[8px] text-[var(--text-muted)]">Actual delivery counters for the selected range.</div></div><Link href="/dashboard/tools/whatsapp-automation" className="rounded-lg bg-[var(--primary)] px-3 py-2 text-[8px] font-bold text-white">OPEN WHATSAPP →</Link></div><div className="grid gap-px bg-[var(--border)] sm:grid-cols-4"><Stat label="WhatsApp sent" value={s.whatsappSent}/><Stat label="Email sent" value={s.emailsSent}/><Stat label="Outbound" value={s.outboundMessages}/><Stat label="Inbound" value={s.inboundMessages}/></div><div className="grid gap-2 p-4 sm:grid-cols-3"><Quick title="WhatsApp" text="Provider, queue, approval and test send." href="/dashboard/tools/whatsapp-automation"/><Quick title="Social Inbox" text="Social leads and conversations." href="/dashboard/tools/social-growth"/><Quick title="Follow-ups" text="Pending and completed follow-ups." href="/dashboard/tools/follow-up-manager"/></div></div><div className="nexor-panel overflow-hidden"><div className="nx-section-head"><div><div className="text-[11px] font-semibold">Social Publishing</div><div className="mt-1 text-[8px] text-[var(--text-muted)]">Published = provider success + external id.</div></div></div><div className="space-y-2 p-4"><Stat label="Published" value={so.published}/><Stat label="Scheduled" value={so.scheduled}/><Stat label="Failed" value={so.failed}/><div className="grid grid-cols-5 gap-1">{[['IG',so.instagram],['FB',so.facebook],['LI',so.linkedin],['YT',so.youtube],['X',so.x]].map(([x,v])=><div key={String(x)} className="rounded-lg bg-[var(--surface-2)] p-2 text-center"><div className="font-mono text-[6px] text-[var(--text-muted)]">{x}</div><div className="mt-1 text-sm font-semibold">{v??0}</div></div>)}</div></div></div></section>
 <section className="grid gap-4 lg:grid-cols-2"><div className="nexor-panel overflow-hidden"><div className="nx-section-head"><div><div className="text-[11px] font-semibold">Integration Matrix</div><div className="mt-1 text-[8px] text-[var(--text-muted)]">Configuration state; provider workspaces report actual runtime success.</div></div></div><div className="grid grid-cols-2 gap-px bg-[var(--border)] sm:grid-cols-3">{Object.entries(ig).map(([name,status])=><div key={name} className="bg-[var(--surface)] p-3"><div className="text-[8px] font-semibold uppercase">{name}</div><div className={`mt-1 font-mono text-[7px] ${status==='CONNECTED'?'text-[var(--success)]':status==='CONFIGURED'?'text-[var(--primary)]':'text-[var(--text-muted)]'}`}>{status}</div></div>)}</div></div><div className="nexor-panel overflow-hidden"><div className="nx-section-head"><div><div className="text-[11px] font-semibold">Founder Controls</div><div className="mt-1 text-[8px] text-[var(--text-muted)]">Persistent identity, automation and developer settings.</div></div><span className={data?.autopilot?.enabled?'nexor-live':'rounded-full border border-[var(--border)] px-2 py-1 font-mono text-[6px] text-[var(--text-muted)]'}>{data?.autopilot?.enabled?'AUTOPILOT ON':'AUTOPILOT PAUSED'}</span></div><div className="grid grid-cols-2 gap-2 p-4"><Quick title="Founder Settings" text="DP, name, theme and appearance." href="/dashboard/settings/studio"/><Quick title="Admin Control Plane" text="50+ advanced persistent controls." href="/dashboard/settings/admin"/><Quick title="Automation" text="Production automation switches." href="/dashboard/settings/automation"/><Quick title="Tool Universe" text="100 registered modules with truthful status." href="#tools"/></div></div></section>
 <section id="tools" className="nexor-panel overflow-hidden"><div className="nx-section-head"><div><div className="text-[11px] font-semibold">Nexor Tool Universe · 60 Core Modules</div><div className="mt-1 text-[8px] text-[var(--text-muted)]">LIVE is reserved for implemented workspaces. CONNECT means provider/engine work remains.</div></div></div><div className="grid gap-px bg-[var(--border)] sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{nexorTools.slice(0,60).map(t=><Link key={t.slug} href={`/dashboard/tools/${t.slug}`} className="bg-[var(--surface)] p-3 hover:bg-[var(--surface-2)]"><div className="flex items-center justify-between gap-2"><div className="truncate text-[9px] font-semibold">{t.name}</div><span className={`rounded-full px-2 py-1 font-mono text-[5px] ${t.status==='ready'?'bg-emerald-500/10 text-emerald-500':'bg-[var(--surface-3)] text-[var(--text-muted)]'}`}>{t.status==='ready'?'LIVE':'CONNECT'}</span></div><div className="mt-1 text-[6px] text-[var(--text-muted)]">{t.group}</div></Link>)}</div></section>
 <section className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="nexor-panel overflow-hidden"><div className="nx-section-head"><div><div className="text-[11px] font-semibold">Live Activity</div><div className="mt-1 text-[8px] text-[var(--text-muted)]">Latest production events in this window.</div></div><label className="flex items-center gap-2 text-[7px] text-[var(--text-muted)]"><input type="checkbox" checked={refresh} onChange={e=>setRefresh(e.target.checked)}/> 30s refresh</label></div><div className="divide-y divide-[var(--border)]">{(data?.activity||[]).slice(0,10).map(a=><div key={a.id} className="flex gap-3 p-3"><span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--primary)]"/><div><div className="text-[9px] font-semibold">{a.type}</div><div className="mt-1 text-[8px] text-[var(--text-secondary)]">{a.message}</div></div></div>)}{!loading&&!data?.activity?.length&&<div className="p-6 text-center text-[9px] text-[var(--text-muted)]">No activity in this range.</div>}</div></div><div className="nexor-panel overflow-hidden"><div className="nx-section-head"><div><div className="text-[11px] font-semibold">Hot Opportunities</div><div className="mt-1 text-[8px] text-[var(--text-muted)]">Highest current audit scores.</div></div></div><div className="divide-y divide-[var(--border)]">{(data?.hotLeads||[]).map(l=><Link key={l.id} href="/dashboard/tools/lead-inbox" className="block p-3 hover:bg-[var(--surface-2)]"><div className="flex justify-between gap-2"><span className="truncate text-[9px] font-semibold">{l.business_name}</span><span className="font-mono text-[8px] text-[var(--primary)]">{l.audit_score}</span></div><div className="mt-1 text-[7px] text-[var(--text-muted)]">{l.niche} · {l.country} · {l.status}</div></Link>)}</div></div></section>
 </main>;
}
