'use client';
import { useEffect, useState } from 'react';

type Mission = { id:string; goal:string; status:string; progress:number; plan:Array<{label:string;workflow:string;approvalRequired:boolean}>; createdAt:string };

export default function GrowthCommandCenter() {
  const [goal,setGoal]=useState(''); const [markets,setMarkets]=useState('USA, Australia, Canada, UAE'); const [limit,setLimit]=useState('25');
  const [missions,setMissions]=useState<Mission[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [result,setResult]=useState('');
  async function load(){ try{const r=await fetch('/api/growth/missions',{cache:'no-store'});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'Unable to load missions');setMissions(d.missions||[]);}catch(e){setError(e instanceof Error?e.message:'Unable to load missions');} }
  useEffect(()=>{void load();},[]);
  async function createAndRun(){if(!goal.trim()||busy)return;setBusy(true);setError('');setResult('');try{const context={markets:markets.split(',').map(x=>x.trim()).filter(Boolean),limit:Number(limit)||25};const r=await fetch('/api/growth/missions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({goal,context,execute:true})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'Mission failed');setResult(`Mission ${d.result?.status||'completed'} · ${d.result?.progress??100}%`);setGoal('');await load();}catch(e){setError(e instanceof Error?e.message:'Mission failed');}finally{setBusy(false);}}
  async function run(id:string){if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/growth/missions',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'Mission failed');await load();}catch(e){setError(e instanceof Error?e.message:'Mission failed');}finally{setBusy(false);}}
  return <section className="space-y-5">
    <div className="nexor-panel overflow-hidden"><div className="border-b border-[var(--border)] px-5 py-4"><div className="font-mono text-[7px] tracking-[.2em] text-[var(--accent)]">AI GROWTH COMMAND CENTER</div><h1 className="mt-2 text-2xl font-semibold tracking-[-.04em]">Give Nexor a business goal.</h1><p className="mt-1 text-[10px] leading-5 text-[var(--text-secondary)]">Nexor turns the goal into an execution plan, runs existing production workflows, persists every step and keeps outbound actions approval-gated.</p></div>
      <div className="p-5"><textarea value={goal} onChange={e=>setGoal(e.target.value)} rows={3} placeholder="Example: Find 25 high-intent dental clinics in the USA and UAE, research their growth gaps, score them and prepare personalized outreach drafts." className="w-full resize-none rounded-xl border border-[var(--border)] bg-[var(--surface-2)] p-4 text-[13px] leading-6 text-[var(--text)] outline-none focus:border-[var(--accent)]/50"/>
      <div className="mt-3 grid gap-3 md:grid-cols-[1fr_120px_auto]"><input value={markets} onChange={e=>setMarkets(e.target.value)} placeholder="Markets" className="rounded-xl border border-[var(--border)] bg-[var(--surface-2)] px-3 py-2.5 text-[9px] text-[var(--text)] outline-none"/><input value={limit} onChange={e=>setLimit(e.target.value)} type="number" min="1" max="50" className="rounded-xl border border-[var(--border)] bg-[var(--surface-2)] px-3 py-2.5 text-[9px] text-[var(--text)] outline-none"/><button disabled={!goal.trim()||busy} onClick={()=>void createAndRun()} className="rounded-xl bg-[var(--accent)] px-5 py-2.5 text-[9px] font-bold tracking-[.12em] text-black disabled:opacity-30">{busy?'EXECUTING...':'PLAN + EXECUTE →'}</button></div>
      {result&&<div className="mt-3 rounded-xl border border-emerald-500/20 bg-emerald-500/[.05] px-4 py-3 text-[9px] text-emerald-400">{result}</div>}{error&&<div className="mt-3 rounded-xl border border-red-500/20 bg-red-500/[.05] px-4 py-3 text-[9px] text-red-400">{error}</div>}
    </div></div>
    <div className="nexor-panel"><div className="border-b border-[var(--border)] px-5 py-4"><div className="text-[11px] font-semibold">Mission history</div><div className="mt-1 text-[8px] text-[var(--text-muted)]">Every mission is persisted with its plan, status and execution result.</div></div><div className="divide-y divide-[var(--border)]">{missions.length?missions.map(m=><div key={m.id} className="p-5"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div className="min-w-0"><div className="text-[11px] font-semibold text-[var(--text)]">{m.goal}</div><div className="mt-2 flex flex-wrap gap-2">{(m.plan||[]).map((s,i)=><span key={`${m.id}-${i}`} className="rounded-lg border border-[var(--border)] bg-[var(--surface-2)] px-2.5 py-1.5 text-[7px] text-[var(--text-secondary)]">{i+1}. {s.label}</span>)}</div></div><div className="flex shrink-0 items-center gap-3"><span className="font-mono text-[8px] text-[var(--text-muted)]">{m.progress}% · {m.status}</span>{m.status==='PLANNED'&&<button onClick={()=>void run(m.id)} disabled={busy} className="rounded-lg border border-[var(--border)] px-3 py-2 text-[8px] font-semibold">RUN</button>}</div></div><div className="mt-3 h-1 overflow-hidden rounded-full bg-[var(--surface-3)]"><div className="h-full bg-[var(--accent)]" style={{width:`${m.progress}%`}}/></div></div>):<div className="px-5 py-10 text-center text-[9px] text-[var(--text-muted)]">No missions yet. Give Nexor a measurable growth goal above.</div>}</div></div>
  </section>;
}
