'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';

const groups = [
  { title: 'COMMAND', items: [['Overview', '/dashboard', '⌂'], ['AIOS Command Center', '/dashboard/aios', '✦'], ['Autopilot', '/dashboard/command', '◈']] },
  { title: 'ACQUISITION', items: [['Lead Generation', '/dashboard/tools/lead-finder', '◎'], ['Leads', '/dashboard/tools/lead-inbox', '◉'], ['Research', '/dashboard/tools/seo-audit', '⌕'], ['Campaigns', '/dashboard/command', '◌'], ['Opportunities', '/dashboard/tools/opportunities', '◇']] },
  { title: 'SALES', items: [['Outreach', '/dashboard/tools/whatsapp-drafts', '↗'], ['WhatsApp', '/dashboard/tools/whatsapp-sending', '◍'], ['Email', '/dashboard/tools/email-drafts', '✉'], ['Inbox', '/dashboard/tools/whatsapp-inbox', '□'], ['CRM', '/dashboard/tools/crm-pipeline', '◫'], ['Follow-ups', '/dashboard/tools/follow-up-manager', '↻'], ['Proposals', '/dashboard/aios#proposals', '▤']] },
  { title: 'SOCIAL', items: [['Social Growth', '/dashboard/tools/social-growth', '✦'], ['Social Hub', '/dashboard/tools/social-scheduler', '◎'], ['Content Calendar', '/dashboard/tools/content-calendar', '◫'], ['Instagram', '/dashboard/tools/instagram-manager', '◎'], ['Facebook', '/dashboard/tools/facebook-manager', '●'], ['LinkedIn', '/dashboard/tools/linkedin-manager', 'in']] },
  { title: 'CREATIVE', items: [['Content Studio', '/dashboard/tools/content-ideas', '✎'], ['Graphics', '/dashboard/tools/social-post-designer', '▧'], ['Ad Creatives', '/dashboard/tools/ad-creative-designer', '◇'], ['Creative Library', '/dashboard/tools/creative-library', '▤']] },
  { title: 'ADVERTISING', items: [['Meta Ads', '/dashboard/tools/meta-ads-overview', 'M'], ['Google Ads', '/dashboard/tools/google-ads-overview', 'G'], ['Optimization', '/dashboard/tools/google-optimization', '↗'], ['ROAS', '/dashboard/tools/meta-roas', '◒']] },
  { title: 'WEB + SEO', items: [['SEO', '/dashboard/tools/seo-audit', '⌕'], ['Analytics', '/dashboard/tools/ga4-analytics', '◒'], ['Websites', '/dashboard/tools/website-projects', '⌘'], ['Landing Pages', '/dashboard/tools/landing-page-builder', '▱'], ['WordPress', '/dashboard/tools/wordpress-manager', 'W']] },
  { title: 'AI OPS', items: [['AI Agents', '/dashboard/tools/ai-agents', '✧'], ['Automations', '/dashboard/tools/automation-center', '⚙'], ['Approvals', '/dashboard/aios#approvals', '✓'], ['Clients', '/dashboard/aios#clients', '◉'], ['Finance', '/dashboard/aios#finance', '₹'], ['Reports', '/dashboard/tools/google-reporting', '▤'], ['Settings', '/dashboard/settings', '⚙']] },
];

export default function Sidebar() {
  const pathname = usePathname();
  return (
    <aside className="sticky top-0 hidden h-screen w-[248px] shrink-0 flex-col border-r border-[var(--border)] bg-[var(--surface)]/95 backdrop-blur-xl lg:flex">
      <div className="flex h-[72px] items-center border-b border-[var(--border)] px-5"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl border border-[var(--accent)]/30 bg-[var(--accent-soft)] text-sm font-bold text-[var(--accent)] shadow-[0_0_24px_rgba(212,175,99,.08)]">N</div><div><div className="text-[13px] font-bold tracking-[0.25em] text-[var(--text)]">NEXOR</div><div className="mt-0.5 font-mono text-[7px] tracking-[0.24em] text-[var(--text-muted)]">AI OPERATING SYSTEM</div></div></div></div>
      <div className="flex-1 overflow-y-auto px-3 py-4">{groups.map((group) => <div key={group.title} className="mb-5"><div className="mb-2 px-3 font-mono text-[7px] font-semibold tracking-[0.22em] text-[var(--text-muted)]">{group.title}</div><div className="space-y-0.5">{group.items.map(([label, href, icon]) => { const active = pathname === href || (href !== '/dashboard' && pathname.startsWith(href)); return <Link key={`${label}-${href}`} href={href} className={['group flex h-8 items-center gap-3 rounded-lg px-3 text-[10px] transition-all', active ? 'bg-[var(--accent-soft)] text-[var(--text)] ring-1 ring-[var(--accent)]/10' : 'text-[var(--text-secondary)] hover:bg-[var(--surface-2)] hover:text-[var(--text)]'].join(' ')}><span className={['w-4 text-center text-[10px]', active ? 'text-[var(--accent)]' : 'text-[var(--text-muted)]'].join(' ')}>{icon}</span><span className="flex-1">{label}</span></Link>; })}</div></div>)}</div>
      <div className="border-t border-[var(--border)] p-3"><div className="mb-3 flex items-center gap-2 rounded-xl border border-emerald-500/15 bg-emerald-500/[0.035] px-3 py-2.5"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400 shadow-[0_0_8px_rgba(52,211,153,.7)]" /><div><div className="text-[8px] font-medium text-[var(--text)]">Systems operational</div><div className="mt-0.5 font-mono text-[6px] text-[var(--text-muted)]">API · DB · AI</div></div></div><div className="flex items-center gap-3 px-2 py-2"><div className="flex h-8 w-8 items-center justify-center rounded-full border border-[var(--accent)]/25 bg-[var(--accent-soft)] text-[10px] font-bold text-[var(--accent)]">D</div><div><div className="text-[9px] font-semibold text-[var(--text)]">Dev</div><div className="text-[7px] text-[var(--text-muted)]">Founder · Nexor</div></div></div></div>
    </aside>
  );
}
