'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import VoiceAssistant from './VoiceAssistant';

type Result = { id:string; name:string; subtitle:string; href:string; kind:'Lead'|'Outreach' };

export default function Topbar(){
 const router=useRouter();const inputRef=useRef<HTMLInputElement>(null);const[dark,setDark]=useState(false);const[open,setOpen]=useState(false);const[q,setQ]=useState('');const[leads,setLeads]=useState<any[]>([]);const[outreach,setOutreach]=useState<any[]>([]);const[loaded,setLoaded]=useState(false);
 useEffect(()=>{const saved=localStorage.getItem('nexor-theme');const d=saved==='dark';document.documentElement.classList.toggle('dark',d);setDark(d)},[]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setOpen(true);setTimeout(()=>inputRef.current?.focus(),0)}if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
 useEffect(()=>{if(!open||loaded)return;Promise.all([fetch('/api/leads',{cache:'no-store'}),fetch('/api/outreach',{cache:'no-store'})]).then(async([a,b])=>{const la=await a.json().catch(()=>({}));const ob=await b.json().catch(()=>({}));setLeads(Array.isArray(la?.data)?la.data:[]);setOutreach(Array.isArray(ob?.outreach)?ob.outreach:Array.isArray(ob?.data)?ob.data:[]);setLoaded(true)}).catch(()=>setLoaded(true))},[open,loaded]);
 const results=useMemo<Result[]>(()=>{const term=q.trim().toLowerCase();if(!term)return[];const a=leads.filter(x=>`${x.businessName||''} ${x.email||''} ${x.niche||''}`.toLowerCase().includes(term)).slice(0,6).map(x=>({id:x.id,name:x.businessName,subtitle:`${x.niche||'Lead'} · ${x.status||'NEW'}`,href:'/dashboard/leads',kind:'Lead' as const}));const b=outreach.filter(x=>`${x.lead?.businessName||''} ${x.channel||''} ${x.status||''}`.toLowerCase().includes(term)).slice(0,6).map(x=>({id:x.id,name:x.lead?.businessName||'Outreach',subtitle:`${x.channel||'OUTREACH'} · ${x.status||'DRAFT'}`,href:'/dashboard/outreach',kind:'Outreach' as const}));return[...a,...b].slice(0,10)},[q,leads,outreach]);
 function toggle(){const n=!dark;document.documentElement.classList.toggle('dark',n);localStorage.setItem('nexor-theme',n?'dark':'light');setDark(n)}
 function close(){setOpen(false);setQ('')}
 return <>
  <header className="sticky top-0 z-50 flex min-h-[58px] items-center justify-between border-b border-[var(--border)] bg-[var(--surface)]/92 px-3 backdrop-blur-xl sm:h-[64px] sm:px-4 lg:px-7">
   <div className="flex min-w-0 items-center gap-2.5"><button onClick={()=>{setOpen(true);setTimeout(()=>inputRef.current?.focus(),0)}} className="flex h-9 w-9 items-center justify-center rounded-[8px] border border-[var(--border)] bg-[var(--surface-2)] text-[var(--text-secondary)] md:hidden" aria-label="Search">⌕</button><button onClick={()=>{setOpen(true);setTimeout(()=>inputRef.current?.focus(),0)}} className="hidden h-9 w-[390px] items-center gap-3 rounded-[8px] border border-[var(--border)] bg-[var(--surface-2)] px-3 text-left md:flex" aria-label="Search Nexor"><span className="text-[var(--text-muted)]">⌕</span><span className="flex-1 text-[10px] text-[var(--text-muted)]">Search leads, outreach, tools…</span><kbd className="rounded border border-[var(--border)] bg-[var(--surface)] px-1.5 py-0.5 font-mono text-[8px] text-[var(--text-muted)]">⌘ K</kbd></button><div className="hidden md:block"><div className="nexor-kicker">NEXORAIOS</div><div className="mt-0.5 text-[10px] font-semibold text-[var(--text)]">Executive command layer</div></div><div className="md:hidden"><div className="nexor-kicker">NEXOR</div><div className="text-[10px] font-semibold">Operating system</div></div></div>
   <div className="flex items-center gap-1.5 sm:gap-2"><VoiceAssistant compact/><div className="hidden items-center gap-2 rounded-full border border-[var(--success)]/15 bg-[var(--success)]/[.035] px-3 py-1.5 sm:flex"><span className="h-1.5 w-1.5 rounded-full bg-[var(--success)]"/><span className="font-mono text-[8px] tracking-[.10em] text-[var(--success)]">LIVE</span></div><button onClick={toggle} aria-label="Toggle theme" className="flex h-9 w-9 items-center justify-center rounded-[8px] border border-[var(--border)] bg-[var(--surface)] text-sm text-[var(--text-secondary)]">{dark?'☼':'☾'}</button><button onClick={()=>{setOpen(true);setTimeout(()=>inputRef.current?.focus(),0)}} className="hidden rounded-[8px] border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-[10px] font-medium text-[var(--text-secondary)] sm:block">✦ Command</button><div className="ml-0.5 flex h-8 w-8 items-center justify-center rounded-full border border-[var(--accent)]/30 bg-[var(--accent-soft)] text-[10px] font-bold text-[var(--accent)] sm:ml-1">D</div></div>
  </header>
  {open&&<div className="fixed inset-0 z-[100] bg-slate-950/25 p-3 backdrop-blur-sm" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="mx-auto mt-[7vh] w-full max-w-2xl overflow-hidden rounded-xl border border-[var(--border-strong)] bg-[var(--surface)] shadow-2xl"><div className="flex items-center gap-3 border-b border-[var(--border)] p-3"><span className="text-[var(--text-muted)]">⌕</span><input ref={inputRef} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search anything in Nexor…" className="h-11 min-w-0 flex-1 bg-transparent text-sm outline-none" autoComplete="off"/><kbd className="rounded border border-[var(--border)] px-2 py-1 text-[9px] text-[var(--text-muted)]">ESC</kbd></div><div className="max-h-[65vh] overflow-auto p-2">{!q&&<div className="grid gap-2 p-2 sm:grid-cols-3">{[['Leads','/dashboard/leads'],['Outreach','/dashboard/outreach'],['Settings Studio','/dashboard/settings/studio']].map(([label,href])=><button key={href} onClick={()=>{close();router.push(href)}} className="rounded-lg border border-[var(--border)] p-4 text-left hover:bg-[var(--surface-2)]"><div className="text-[11px] font-semibold">{label}</div><div className="mt-1 text-[8px] text-[var(--text-muted)]">Open workspace →</div></button>)}</div>}{q&&results.map(r=><button key={`${r.kind}-${r.id}`} onClick={()=>{close();router.push(r.href)}} className="flex w-full items-center justify-between gap-3 rounded-lg p-3 text-left hover:bg-[var(--surface-2)]"><div className="min-w-0"><div className="truncate text-[11px] font-semibold">{r.name}</div><div className="mt-1 truncate text-[8px] text-[var(--text-muted)]">{r.subtitle}</div></div><span className="shrink-0 rounded-full border border-[var(--border)] px-2 py-1 font-mono text-[7px] text-[var(--text-muted)]">{r.kind}</span></button>)}{q&&loaded&&!results.length&&<div className="p-8 text-center text-[10px] text-[var(--text-muted)]">No matching leads or outreach found.</div>}{q&&!loaded&&<div className="p-8 text-center text-[10px] text-[var(--text-muted)]">Loading Nexor index…</div>}</div></div></div>}
 </>
}
