'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import DashboardLayout from '@/components/dashboard/DashboardLayout';

type Setting={key:string;label:string;enabled:boolean};
type Health={provider?:{configured:boolean;openwaConfigured:boolean;templateConfigured:boolean;automationReady?:boolean};stats?:{sent:number;failed:number;approved:number;scheduled:number;drafts:number}};
const core=['master_autopilot','outbound_enabled','campaign_discovery','whatsapp_generation','whatsapp_sending','followups','outreach','social_publishing','daily_reports'];

export default function AutopilotHQ(){
 const [settings,setSettings]=useState<Setting[]>([]);const [health,setHealth]=useState<Health|null>(null);const [busy,setBusy]=useState('');const [error,setError]=useState('');
 const load=useCallback(async()=>{try{const [s,w]=await Promise.all([fetch('/api/automations/settings',{cache:'no-store'}),fetch('/api/whatsapp/automation',{cache:'no-store'})]);const sj=await s.json();const wj=await w.json();if(!s.ok||!sj.success)throw new Error(sj.error||'Automation settings unavailable');setSettings(sj.settings||[]);setHealth(wj.success?wj:null);setError('')}catch(e){setError(e instanceof Error?e.message:String(e))}},[]);
 useEffect(()=>{void load();const t=window.setInterval(()=>void load(),15000);return()=>window.clearInterval(t)},[load]);
 async function toggle(key:string,enabled:boolean){setBusy(key);setError('');try{const r=await fetch('/api/automations/settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({key,enabled})});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error||'Unable to change setting');setSettings(x=>x.map(s=>s.key===key?{...s,enabled}:s))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
 const master=settings.find(x=>x.key==='master_autopilot')?.enabled??true;const rows=settings.filter(x=>core.includes(x.key)&&x.key!=='master_autopilot');
 return <DashboardLayout><main className="mx-auto w-full max-w-6xl space-y-4 sm:space-y-5">
  <section className="nexor-panel overflow-hidden"><div className="p-5 sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="font-mono text-[7px] tracking-[.2em] text-[var(--accent)]">NEXOR · AUTONOMOUS OPERATING SYSTEM</div><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em]">Autopilot HQ</h1><p className="mt-2 max-w-2xl text-[10px] leading-5 text-[var(--text-secondary)]">One switch for the machine. Nexor can discover, research, qualify, prepare outreach, send eligible messages, run follow-ups, publish connected social content and report outcomes — subject to provider permissions and communication safety rules.</p></div><div className="flex items-center gap-3 rounded-2xl border border-[var(--border)] bg-[var(--surface-2)] p-3"><div><div className="font-mono text-[7px] tracking-[.14em] text-[var(--text-muted)]">MASTER AUTOPILOT</div><div className={`mt-1 text-sm font-semibold ${master?'text-emerald-500':'text-amber-500'}`}>{master?'RUNNING':'PAUSED'}</div></div><button disabled={busy==='master_autopilot'} onClick={()=>void toggle('master_autopilot',!master)} className={`relative h-8 w-14 rounded-full ${master?'bg-[var(--primary)]':'bg-[var(--surface-3)]'}`}><span className={`absolute top-1 h-6 w-6 rounded-full bg-white transition ${master?'left-7':'left-1'}`}/></button></div></div></div>
   <div className="grid grid-cols-2 border-t border-[var(--border)] sm:grid-cols-4"><div className="p-4"><div className="font-mono text-[7px] text-[var(--text-muted)]">SENT</div><div className="mt-1 text-2xl font-semibold">{health?.stats?.sent??0}</div></div><div className="border-l border-[var(--border)] p-4"><div className="font-mono text-[7px] text-[var(--text-muted)]">QUEUED</div><div className="mt-1 text-2xl font-semibold">{(health?.stats?.approved??0)+(health?.stats?.scheduled??0)}</div></div><div className="border-t border-[var(--border)] p-4 sm:border-l sm:border-t-0"><div className="font-mono text-[7px] text-[var(--text-muted)]">FAILED</div><div className="mt-1 text-2xl font-semibold">{health?.stats?.failed??0}</div></div><div className="border-l border-t border-[var(--border)] p-4 sm:border-t-0"><div className="font-mono text-[7px] text-[var(--text-muted)]">PROVIDER</div><div className="mt-1 text-sm font-semibold">{health?.provider?.automationReady?'READY':'CHECK'}</div></div></div></section>
  {error&&<div className="nx-feedback">{error}</div>}
  <section className="grid gap-4 lg:grid-cols-[1fr_320px]"><div className="nexor-panel overflow-hidden"><div className="nx-section-head"><div><div className="text-[11px] font-semibold">Autonomous capabilities</div><div className="mt-1 text-[8px] text-[var(--text-muted)]">Each switch is persisted in the production database.</div></div><span className="nx-live-dot">LIVE</span></div><div className="divide-y divide-[var(--border)]">{rows.map(item=><div key={item.key} className="flex items-center gap-4 p-4"><div className="min-w-0 flex-1"><div className="text-[10px] font-semibold">{item.label}</div><div className="mt-1 font-mono text-[7px] text-[var(--text-muted)]">{item.enabled?'ENABLED':'PAUSED'}</div></div><button disabled={busy===item.key||!master} onClick={()=>void toggle(item.key,!item.enabled)} className={`relative h-7 w-12 shrink-0 rounded-full ${item.enabled&&master?'bg-[var(--primary)]':'bg-[var(--surface-3)]'} disabled:opacity-50`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${item.enabled&&master?'left-6':'left-1'}`}/></button></div>)}</div></div>
   <div className="space-y-4"><section className="nexor-panel p-5"><div className="text-[11px] font-semibold">Night mode</div><p className="mt-2 text-[9px] leading-5 text-[var(--text-secondary)]">Workers continue without a prompt. Commercial sends remain constrained by eligible lead status, recorded WhatsApp opt-in, provider configuration, daily limits and quiet hours.</p><div className="mt-3 rounded-xl bg-[var(--surface-2)] p-3 font-mono text-[8px] text-[var(--text-muted)]">WORKER · EVERY 5 MINUTES</div></section><section className="nexor-panel p-5"><div className="text-[11px] font-semibold">Go directly to</div><div className="mt-3 grid gap-2"><Link className="nx-chip" href="/dashboard/tools/lead-inbox">Lead Inbox →</Link><Link className="nx-chip" href="/dashboard/tools/whatsapp-sending">WhatsApp Control Room →</Link><Link className="nx-chip" href="/dashboard/tools/social-growth">Social OS →</Link><Link className="nx-chip" href="/dashboard/settings/studio">Settings Studio →</Link></div></section></div></section>
 </main></DashboardLayout>;
}
