import { NEXOR_BRAND } from '@nexor/shared';
import { getDatabaseClients } from '@nexor/database';
import { getCommandCenter, ensureAiosPlatform, writeAudit, createApproval } from './aios-platform';
import { buildSalesSequence } from './sales-message-engine';

export type GrowthToolAction = 'LEAD_HUNTER'|'WEBSITE_AUDIT'|'SOCIAL_AUDIT'|'OUTREACH'|'FOLLOW_UP'|'QUALIFY'|'PROPOSAL'|'DEAL'|'TREND_RADAR'|'CONTENT_FACTORY'|'REEL_SCRIPT'|'CREATIVE_DIRECTOR'|'CONTENT_CALENDAR'|'PERFORMANCE_LEARNER'|'REPURPOSE'|'COMPETITOR_WATCH'|'CEO_BRIEF'|'ASK_NEXOR'|'TASK_PRIORITIZER'|'AI_MEMORY'|'RISK_RADAR'|'CASHFLOW'|'INVOICE_REMINDER'|'PROFITABILITY'|'PNL'|'PAYMENT_FOLLOWUP'|'CLIENT_HEALTH'|'REPORT'|'RENEWAL';
const s=(v:unknown,f='')=>String(v??f).trim(); const n=(v:unknown,f=0)=>Number(v??f); const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
async function rows<T>(q:string,f:T[]=[]){try{return await getDatabaseClients().read.$queryRawUnsafe<T[]>(q)}catch{return f}}

export async function runGrowthTool(action:GrowthToolAction,input:Record<string,unknown>={},userId?:string):Promise<Record<string, unknown>>{
 await ensureAiosPlatform(); const brand=NEXOR_BRAND.name; const business=s(input.businessName||input.companyName,'Target business'); const website=s(input.website); const industry=s(input.industry,'business');
 switch(action){
 case 'LEAD_HUNTER':{const leads=await getDatabaseClients().read.lead.findMany({orderBy:[{auditScore:'desc'},{createdAt:'desc'}],take:clamp(n(input.limit,25),1,100)});return{action,count:leads.length,prospects:leads.map(x=>({id:x.id,businessName:x.businessName,website:x.website,country:x.country,score:x.auditScore,email:x.email,whatsapp:x.whatsapp,status:x.status}))}}
 case 'WEBSITE_AUDIT':return website?{action,business,website,findings:['Conversion clarity','Mobile UX','Trust signals','Lead capture','Local visibility','Social proof','Performance','SEO basics'].map((x,i)=>({priority:i<3?'HIGH':'MEDIUM',area:x,recommendation:`Review ${x.toLowerCase()} and turn the finding into one concrete growth action.`})),salesAngle:`Offer a focused ${brand} growth audit.`}:{action,status:'INPUT_REQUIRED',message:'Provide website URL.'};
 case 'SOCIAL_AUDIT':return{action,business,platform:s(input.platform,'Instagram'),findings:['Posting consistency','Content mix','Profile CTA','Hook quality','Lead capture'],opportunities:['Short-form video','Educational series','Offer-led content','Stronger CTA','Content repurposing']};
 case 'OUTREACH':{const channel=s(input.channel,'WHATSAPP').toUpperCase() as 'WHATSAPP'|'EMAIL'|'INSTAGRAM'|'FACEBOOK'|'LINKEDIN';return{action,approvalRequired:true,sequence:buildSalesSequence({businessName:business,contactName:s(input.contactName),website,service:s(input.service,'growth marketing'),requirement:s(input.requirement),findings:s(input.findings),country:s(input.country),channel})}}
 case 'FOLLOW_UP':return{action,sequence:[1,3,7,14].map((day,i)=>({day,stage:['FIRST_TOUCH','FOLLOW_UP_1','FOLLOW_UP_2','BREAKUP'][i],rule:i===3?'Close the loop politely.':'Add value; stop immediately if the prospect replies or opts out.'}))};
 case 'QUALIFY':{const r=s(input.reply),neg=/(no thanks|not interested|unsubscribe|remove me|stop)/i.test(r),pos=/(interested|yes|sure|send|price|pricing|call|meeting|details|let.?s talk)/i.test(r);return{action,classification:neg?'COLD':pos?'HOT':'WARM',score:neg?10:pos?85:50,nextAction:neg?'STOP_OUTREACH':pos?'CREATE_TASK_AND_BOOK_MEETING':'FOLLOW_UP_WITH_VALUE'}}
 case 'PROPOSAL':return{action,status:'DRAFT',approvalRequired:true,proposal:{brand,client:business,problem:s(input.problem,'Improve acquisition and conversion.'),strategy:s(input.strategy,'Integrated growth plan with measurable milestones.'),deliverables:Array.isArray(input.deliverables)?input.deliverables:[s(input.service,'Growth Marketing'),'Monthly reporting','Optimization'],timeline:s(input.timeline,'30-day initial sprint'),pricing:input.pricing??null,nextStep:'Review and approve before sending.'}};
 case 'DEAL':return{action,stages:['PROPOSAL','NEGOTIATION','WON','LOST'],rule:'Advance only from verified CRM events.'};
 case 'TREND_RADAR':return{action,trends:['Short-form educational video','Founder-led authority','Problem/solution carousels','Audit content','AI workflow demos'],industry};
 case 'CONTENT_FACTORY':{const topic=s(input.topic,`${industry} growth mistakes businesses should avoid`);return{action,topic,reel:`Hook → problem → 3 practical points → CTA for ${brand}`,carousel:['Hook','Problem','Insight 1','Insight 2','Insight 3','CTA'],linkedin:`Authority post about ${topic}.`,facebook:`Practical post about ${topic}.`,caption:`${topic}. Save this checklist.`,hashtags:NEXOR_BRAND.defaultHashtags}}
 case 'REEL_SCRIPT':{const topic=s(input.topic,'Why businesses lose leads after generating them');return{action,topic,hook:'You are not losing leads because you need more leads.',scenes:['0-3s hook','3-8s problem','8-18s three fixes','18-25s workflow','25-30s CTA'],voiceover:`Explain ${topic} clearly without invented statistics.`,cta:'DM Nexor for a focused growth audit.'}}
 case 'CREATIVE_DIRECTOR':return{action,status:'BRIEF_READY',inspirationRule:'Public inspiration only; final creative must be original.',brief:{format:s(input.format,'9:16 Reel'),concept:s(input.topic,'AI-powered growth workflow'),visualDirection:'Premium agency aesthetic with clean typography and product moments.',hook:s(input.hook,'What if your agency could do this automatically?'),scenes:['Problem','AI workflow','Result state','CTA'],brand}};
 case 'CONTENT_CALENDAR':{const days=clamp(n(input.days,30),1,60),p=['EDUCATION','PROOF','AUTHORITY','OFFER','FOUNDER','FAQ','BEHIND_THE_SCENES'];return{action,days,calendar:Array.from({length:days},(_,i)=>({day:i+1,pillar:p[i%p.length],format:['REEL','CAROUSEL','LINKEDIN','STATIC'][i%4],status:'DRAFT'}))}}
 case 'PERFORMANCE_LEARNER':{const r=await rows<{platform:string;status:string;count:bigint}>(`SELECT platform::text,status::text,count(*)::bigint AS count FROM public.content_posts GROUP BY platform,status`);return{action,data:r.map(x=>({...x,count:Number(x.count)})),rule:'Use provider analytics for performance/ROI; post counts alone do not prove results.'}}
 case 'REPURPOSE':{const source=s(input.content,s(input.topic,'Source content'));return{action,source,variants:['30-second Reel','Carousel','LinkedIn post','Facebook post','Instagram caption','Story sequence','Email newsletter','X post','FAQ answer','Lead magnet outline']}}
 case 'COMPETITOR_WATCH':return{action,competitor:business,publicInputs:['website','social activity','offers','content themes'],outputs:['positioning gaps','content gaps','offer gaps','differentiation ideas']};
 case 'CEO_BRIEF':{const c=await getCommandCenter();return{action,commandCenter:c,priorities:[c.operations.followUpsDue?'Clear follow-ups due today.':'No overdue follow-ups detected.',c.operations.pendingApprovals?'Review pending approvals.':'Approval queue is clear.',c.sales.qualified?'Advance qualified leads.':'Generate and research more prospects.']}}
 case 'ASK_NEXOR':{const q=s(input.question).toLowerCase(),c=await getCommandCenter();if(/lead|prospect/.test(q))return{answer:`${c.sales.leads} leads, ${c.sales.qualified} qualified, ${c.sales.won} won.`,data:c.sales};if(/revenue|money|pipeline/.test(q))return{answer:`Pipeline ${c.sales.pipeline}; weighted expected revenue ${c.sales.expectedRevenue}.`,data:c.finance};return{answer:`${c.operations.followUpsDue} follow-ups and ${c.operations.tasksDue} due tasks need attention.`,data:c.operations}}
 case 'TASK_PRIORITIZER':{const r=await rows<{id:string;title:string;due_at:string|null}>(`SELECT id::text,title,due_at::text FROM public.tasks WHERE status <> 'COMPLETED' ORDER BY due_at ASC NULLS LAST LIMIT 50`);return{action,tasks:r.map((x,i)=>({...x,priority:i<5?'HIGH':'NORMAL'}))}}
 case 'AI_MEMORY':{const id=s(input.leadId);if(!id)return{action,status:'INPUT_REQUIRED',message:'Provide leadId.'};const safe=id.replace(/'/g,"''");const r=await rows<Record<string,unknown>>(`SELECT id::text,"businessName","website","status","auditScore","createdAt"::text FROM public.leads WHERE id='${safe}' LIMIT 1`);return{action,memory:r[0]??null,source:'CRM'}}
 case 'RISK_RADAR':{const c=await getCommandCenter();return{action,risks:[...(c.operations.followUpsDue?[{severity:'HIGH',issue:`${c.operations.followUpsDue} follow-ups due.`}]:[]),...(c.operations.pendingApprovals?[{severity:'MEDIUM',issue:`${c.operations.pendingApprovals} approvals waiting.`}]:[]),...(c.finance.outstanding?[{severity:'MEDIUM',issue:`${c.finance.outstanding} outstanding.`}]:[])]}}
 case 'CASHFLOW':{const r=await rows<{status:string;total:string}>(`SELECT status,COALESCE(SUM(total),0)::text total FROM public.aios_invoices GROUP BY status`);return{action,invoices:r,paid:(await rows<{total:string}>(`SELECT COALESCE(SUM(amount),0)::text total FROM public.aios_payments WHERE status IN ('RECORDED','CONFIRMED')`,[{total:'0'}]))[0].total}}
 case 'INVOICE_REMINDER':case 'PAYMENT_FOLLOWUP':return{action,approvalRequired:true,message:`Hi ${business}, a quick reminder regarding ${s(input.amount,'the outstanding balance')}. Please let us know if you need the details resent. Thank you — ${brand}.`};
 case 'PROFITABILITY':{const revenue=n(input.revenue),cost=n(input.cost);return{action,revenue,cost,grossProfit:revenue-cost,margin:revenue?((revenue-cost)/revenue)*100:0}}
 case 'PNL':{const revenue=n(input.revenue),expenses=n(input.expenses);return{action,revenue,expenses,net:revenue-expenses,margin:revenue?((revenue-expenses)/revenue)*100:0}}
 case 'CLIENT_HEALTH':{const signals={communication:clamp(n(input.communication,50),0,100),delivery:clamp(n(input.delivery,50),0,100),performance:clamp(n(input.performance,50),0,100),payment:clamp(n(input.payment,50),0,100)},score=Math.round(Object.values(signals).reduce((a,b)=>a+b,0)/4);return{action,client:business,score,status:score>=75?'HEALTHY':score>=50?'WATCH':'AT_RISK',signals,nextAction:score<50?'Schedule client-success review.':'Continue current cadence.'}}
 case 'REPORT':{const c=await getCommandCenter();return{action,client:business,generatedAt:new Date().toISOString(),sections:['Executive summary','Campaign performance','Lead pipeline','Social content','Finance','Next actions'],data:c}}
 case 'RENEWAL':{const health=await runGrowthTool('CLIENT_HEALTH',input,userId);return{action,client:business,health,recommendation:health.status==='HEALTHY'?'Prepare renewal/expansion proposal.':'Resolve client risks before renewal conversation.'}}
 default:throw new Error(`Unsupported growth tool: ${action}`)
 }
}
export async function queueGrowthApproval(action:string,payload:unknown,userId?:string){const id=await createApproval({action,targetType:'GROWTH_TOOL',payload,reason:'External side effect requires explicit approval.',userId});if(userId)await writeAudit({userId,action:'GROWTH_TOOL_QUEUED',targetType:'GROWTH_TOOL',targetId:id,after:payload});return id}
