import { NextRequest, NextResponse } from 'next/server';
import { getDatabaseClients, LeadStatus, OutreachChannel, OutreachStatus } from '@nexor/database';
import { outreachService } from '@nexor/ai';
import { getSessionUser } from '@/lib/auth';
import { sendApprovedOutreach } from '@/lib/outreach-sender';

function getPrisma(){return getDatabaseClients().write;}
const BLOCKED_NAME=[/\bjobs?\b/i,/\bvacanc(?:y|ies)\b/i,/\bcareers?\b/i,/\bhiring\b/i,/\bsalary\b/i,/\bapply now\b/i,/\bresume\b/i,/\bcv\b/i,/\binternship\b/i,/\brecruitment\b/i,/\btop\b/i,/\bbest\b/i,/\blist\b/i,/\bdirectory\b/i,/\bguide\b/i,/\broundup\b/i,/\barticle\b/i,/\bnews\b/i,/\bhow to\b/i];
const NON_BUSINESS_PATHS=/\/(jobs?|careers?|vacancies|blog|article|news|category|tag|search|directory|listing|forum|forums)(\/|$)/i;
const VALID_LEAD_TYPES=new Set(['BUSINESS','COMPANY','LOCAL_BUSINESS','AGENCY','PROFESSIONAL_SERVICE']);
const BLOCKED_SOURCES=new Set(['JOB','JOB_SEARCH','JOB-SEARCH','RECRUITMENT','CAREER','JOB_PORTAL']);
const APPROVAL_STATUSES: OutreachStatus[]=[OutreachStatus.DRAFT,OutreachStatus.APPROVAL_REQUIRED];
const ACTIVE_STATUSES: OutreachStatus[]=[OutreachStatus.DRAFT,OutreachStatus.APPROVAL_REQUIRED,OutreachStatus.APPROVED,OutreachStatus.SCHEDULED];
function parseNotes(notes:string|null){try{const p=notes?JSON.parse(notes):{};return p&&typeof p==='object'?p as Record<string,any>:{};}catch{return{};}}
function validateBusinessLead(lead:{businessName:string;website:string|null;notes:string|null;whatsapp:string|null}){const parsed=parseNotes(lead.notes),m=parsed.metadata??parsed;const leadType=typeof m.leadType==='string'?m.leadType.toUpperCase():'';const source=typeof m.source==='string'?m.source.toUpperCase():'';if(!lead.businessName.trim()||BLOCKED_NAME.some(p=>p.test(lead.businessName)))return{ok:false,reason:'Blocked job/content/non-business lead'};if(BLOCKED_SOURCES.has(source)||(leadType&&!VALID_LEAD_TYPES.has(leadType)))return{ok:false,reason:`Blocked lead type/source: ${leadType||'unknown'} / ${source||'unknown'}`};if(lead.website){try{if(NON_BUSINESS_PATHS.test(new URL(lead.website).pathname))return{ok:false,reason:'Blocked job/content/listing website'}}catch{return{ok:false,reason:'Invalid lead website'}}}return{ok:true,leadType:leadType||'BUSINESS',source:source||'UNKNOWN',parsed};}
async function authorized(req:NextRequest){const secret=process.env.OUTREACH_API_SECRET?.trim();if(secret&&req.headers.get('authorization')===`Bearer ${secret}`)return true;return Boolean(await getSessionUser(req));}
function normalizeChannel(v:unknown):OutreachChannel|null{return Object.values(OutreachChannel).includes(v as OutreachChannel)?v as OutreachChannel:null;}
function buildMessage(channel:OutreachChannel,lead:{businessName:string;ownerName:string|null},context:string){const name=lead.ownerName||lead.businessName;if(channel===OutreachChannel.EMAIL)return`Subject: A quick growth observation for ${lead.businessName}\n\nHi ${name},\n\nI had a look at ${lead.businessName} and noticed a few opportunities around online lead generation. ${context}\n\nI can share the specific opportunities and a practical action plan if useful.\n\nRegards,\nNexor Media`;return`Hi ${name}, I was looking at ${lead.businessName} and noticed a few opportunities to improve online lead generation. ${context} I can send you the specific ideas if you'd like. — Nexor Media`;}
function cleanWhatsAppMessage(value:string){let s=value.replace(/^```(?:text|markdown)?/i,'').replace(/```$/,'').trim();const markers=['Verified research:','Verified scoring:','Research context:','Here is the verified research'];for(const marker of markers){const i=s.indexOf(marker);if(i>30)s=s.slice(0,i).trim();}s=s.replace(/\{\s*"success"\s*:\s*true[\s\S]*$/,'').trim();if(s.length>1200)s=`${s.slice(0,1180).replace(/\s+$/,'')}…`;return s;}

export async function GET(req:NextRequest){if(!(await authorized(req)))return NextResponse.json({success:false,error:'Unauthorized'},{status:401});const prisma=getPrisma();try{const drafts=await prisma.outreach.findMany({where:{status:{in:APPROVAL_STATUSES}},include:{lead:true,campaign:true},orderBy:{createdAt:'asc'},take:200});return NextResponse.json({success:true,count:drafts.length,drafts});}catch(error){return NextResponse.json({success:false,error:error instanceof Error?error.message:String(error)},{status:500});}}

export async function POST(req:NextRequest){if(!(await authorized(req)))return NextResponse.json({success:false,error:'Unauthorized'},{status:401});try{const prisma=getPrisma();const body=await req.json();const leadId=typeof body.leadId==='string'?body.leadId:'';const channel=normalizeChannel(body.channel);const context=typeof body.context==='string'?body.context.trim():'';const supported: OutreachChannel[]=[OutreachChannel.WHATSAPP,OutreachChannel.EMAIL,OutreachChannel.INSTAGRAM,OutreachChannel.FACEBOOK,OutreachChannel.LINKEDIN];if(!leadId||!channel||!supported.includes(channel))return NextResponse.json({success:false,error:'leadId and a supported outreach channel are required'},{status:400});const lead=await prisma.lead.findUnique({where:{id:leadId}});if(!lead)return NextResponse.json({success:false,error:'Lead not found'},{status:404});const validation=validateBusinessLead(lead);if(!validation.ok)return NextResponse.json({success:false,error:validation.reason},{status:422});if(channel===OutreachChannel.WHATSAPP&&!lead.whatsapp)return NextResponse.json({success:false,error:'NOT CONTACTABLE: WhatsApp number missing'},{status:422});const existing=await prisma.outreach.findFirst({where:{leadId,channel,status:{in:ACTIVE_STATUSES}},orderBy:{createdAt:'desc'}});if(existing)return NextResponse.json({success:true,duplicate:true,outreach:existing});let message='';if(channel===OutreachChannel.WHATSAPP){const p=validation.parsed??{};const generated=await outreachService.generate({businessName:lead.businessName,ownerName:lead.ownerName,niche:lead.niche,country:lead.country,website:lead.website,whatsapp:lead.whatsapp,auditScore:lead.auditScore,notes:lead.notes,verifiedResearch:p.research??{},verifiedScore:p.score??{},leadMetadata:{leadType:validation.leadType,source:validation.source},uniquenessInstruction:`Write only the final first-contact WhatsApp message for ${lead.businessName}. Never output research JSON, scoring JSON, analysis labels, markdown fences, or internal notes. Use one or two specific verified findings only. ${context}`});message=cleanWhatsAppMessage(typeof generated?.whatsapp==='string'?generated.whatsapp.trim():'');if(!message)return NextResponse.json({success:false,error:'AI could not produce a clean personalized WhatsApp draft'},{status:502});}else message=buildMessage(channel,lead,context||'Your current digital presence looks like it has room for measurable improvements.');const outreach=await prisma.$transaction(async tx=>{const created=await tx.outreach.create({data:{leadId,channel,status:OutreachStatus.APPROVAL_REQUIRED,message}});await tx.lead.update({where:{id:leadId},data:{status:LeadStatus.PITCH_READY}});return created;});return NextResponse.json({success:true,outreach},{status:201});}catch(error){return NextResponse.json({success:false,error:error instanceof Error?error.message:String(error)},{status:500});}}

export async function PATCH(req:NextRequest){if(!(await authorized(req)))return NextResponse.json({success:false,error:'Unauthorized'},{status:401});try{const prisma=getPrisma();const body=await req.json();const id=typeof body.id==='string'?body.id:'';const action=body.action==='approve'?'approve':body.action==='cancel'?'cancel':'';if(!id||!action)return NextResponse.json({success:false,error:'id and action are required'},{status:400});const existing=await prisma.outreach.findUnique({where:{id},include:{lead:true}});if(!existing)return NextResponse.json({success:false,error:'Outreach not found'},{status:404});if(!APPROVAL_STATUSES.includes(existing.status))return NextResponse.json({success:false,error:`Outreach is not awaiting approval. Current status: ${existing.status}`},{status:409});if(action==='approve'){const validation=validateBusinessLead(existing.lead);if(!validation.ok)return NextResponse.json({success:false,error:validation.reason},{status:422});if(existing.channel===OutreachChannel.WHATSAPP&&!existing.lead.whatsapp)return NextResponse.json({success:false,error:'NOT CONTACTABLE: WhatsApp number missing'},{status:422});}
 const draft=await prisma.outreach.update({where:{id},data:{status:action==='approve'?OutreachStatus.APPROVED:OutreachStatus.CANCELLED,approvedAt:action==='approve'?new Date():null,scheduledAt:action==='approve'?new Date(Date.now()+15000):null,error:null}});
 if(action==='approve'&&draft.channel===OutreachChannel.WHATSAPP){try{const result=await sendApprovedOutreach(id);return NextResponse.json({success:true,draft:result.outreach,sendResult:{sent:!result.alreadySent,recipient:result.recipient}});}catch(error){const current=await prisma.outreach.findUnique({where:{id}});return NextResponse.json({success:false,error:error instanceof Error?error.message:String(error),draft:current},{status:502});}}
 return NextResponse.json({success:true,draft,autoSendAt:draft.scheduledAt});
 }catch(error){return NextResponse.json({success:false,error:error instanceof Error?error.message:String(error)},{status:500});}}
