import Link from 'next/link';
import DashboardLayout from '@/components/dashboard/DashboardLayout';
import { getDatabaseClients, LeadStatus, OutreachStatus, CampaignStatus } from '@nexor/database';

async function getSummary(){
  try{
    const db=getDatabaseClients().write;
    const [leads,qualified,replies,meetings,won,drafts,sent,campaigns]=await Promise.all([
      db.lead.count(),db.lead.count({where:{status:LeadStatus.QUALIFIED}}),db.lead.count({where:{status:LeadStatus.REPLIED}}),
      db.lead.count({where:{status:LeadStatus.MEETING_BOOKED}}),db.lead.count({where:{status:LeadStatus.WON}}),
      db.outreach.count({where:{status:{in:[OutreachStatus.DRAFT,OutreachStatus.APPROVAL_REQUIRED]}}}),
      db.outreach.count({where:{status:OutreachStatus.SENT}}),db.campaign.count({where:{status:CampaignStatus.RUNNING}})
    ]);
    return {leads,qualified,replies,meetings,won,drafts,sent,campaigns,db:true};
  }catch{return {leads:0,qualified:0,replies:0,meetings:0,won:0,drafts:0,sent:0,campaigns:0,db:false};}
}

const nav=[
 ['Lead Generation','/dashboard/tools/lead-finder'],['Leads','/dashboard/tools/lead-inbox'],['Research','/dashboard/tools/seo-audit'],['CRM','/dashboard/tools/crm-pipeline'],
 ['Outreach','/dashboard/tools/whatsapp-drafts'],['WhatsApp','/dashboard/tools/whatsapp-inbox'],['Meta Ads','/dashboard/tools/meta-ads-overview'],['Google Ads','/dashboard/tools/google-ads-overview'],
 ['Websites','/dashboard/tools/website-projects'],['Reports','/dashboard/tools/google-reporting'],['AI Agents','/dashboard/tools/ai-agents'],['Automations','/dashboard/tools/automation-center']
] as const;

function Spark(){return <div className="flex h-6 items-end gap-1 opacity-70">{[24,42,31,55,47,72,61,86].map((h,i)=><span key={i} className="w-1 rounded-t bg-[var(--accent)]" style={{height:`${h}%`}}/>)}</div>}

export default async function Dashboard(){
 const s=await getSummary(); const q=s.leads?Math.round(s.qualified/s.leads*100):0; const r=s.qualified?Math.round(s.replies/s.qualified*100):0; const m=s.replies?Math.round(s.meetings/s.replies*100):0; const w=s.meetings?Math.round(s.won/s.meetings*100):0;
 const kpis=[['LEADS',s.leads,`${q}% qualified`,'/dashboard/tools/lead-inbox'],['QUALIFIED',s.qualified,'sales-ready','/dashboard/tools/lead-inbox'],['REPLIES',s.replies,`${r}% reply rate`,'/dashboard/tools/whatsapp-inbox'],['MEETINGS',s.meetings,`${m}% from replies`,'/dashboard/tools/follow-up-manager'],['WON',s.won,`${w}% from meetings`,'/dashboard/tools/crm-pipeline']] as const;
 const funnel=[['LEADS',s.leads,100],['QUALIFIED',s.qualified,q],['REPLIED',s.replies,r],['MEETINGS',s.meetings,m],['WON',s.won,w]] as const;
 return <DashboardLayout><main className="min-h-full pb-12">
  <header className="border-b border-[var(--border)] pb-6 pt-1"><div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><div className="mb-3 flex items-center gap-2 font-mono text-[8px] font-semibold tracking-[.22em] text-[var(--accent)]"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400"/>NEXOR AIOS · EXECUTIVE CONTROL</div><h1 className="text-[34px] font-semibold tracking-[-.045em] sm:text-[42px]">Good evening, Dev.</h1><p className="mt-2 text-[13px] text-[var(--text-secondary)]">Your entire growth operation, distilled into the decisions that matter.</p></div><div className="flex gap-2"><div className="rounded-lg border border-[var(--border)] bg-[var(--surface)] px-3 py-2 font-mono text-[8px] text-[var(--text-muted)]">AUG 31 · 2026</div><Link href="/dashboard/command" className="rounded-lg bg-[var(--text)] px-4 py-2.5 text-[10px] font-semibold text-[var(--bg)] transition hover:-translate-y-px">⌘ Open command</Link></div></div>
   <div className="mt-6 grid gap-px overflow-hidden rounded-xl border border-[var(--border)] bg-[var(--border)] sm:grid-cols-3"><div className="bg-[var(--surface)] px-4 py-3"><div className="font-mono text-[7px] tracking-[.17em] text-[var(--text-muted)]">SYSTEM STATUS</div><div className="mt-1.5 flex items-center gap-2 text-[10px] font-medium"><span className={`h-1.5 w-1.5 rounded-full ${s.db?'bg-emerald-400':'bg-amber-400'}`}/>{s.db?'Core systems operational':'Database configuration required'}</div></div><div className="bg-[var(--surface)] px-4 py-3"><div className="font-mono text-[7px] tracking-[.17em] text-[var(--text-muted)]">OPERATOR QUEUE</div><div className="mt-1.5 text-[10px] font-medium">{s.drafts} outreach items awaiting approval</div></div><div className="bg-[var(--surface)] px-4 py-3"><div className="font-mono text-[7px] tracking-[.17em] text-[var(--text-muted)]">ACQUISITION</div><div className="mt-1.5 text-[10px] font-medium">{s.campaigns} campaigns currently running</div></div></div>
  </header>

  <section className="border-b border-[var(--border)] py-5"><div className="mb-3 flex justify-between"><span className="font-mono text-[8px] font-semibold tracking-[.2em] text-[var(--text-muted)]">OPERATING METRICS</span><span className="font-mono text-[7px] text-[var(--text-muted)]">LIVE · DATABASE SYNC</span></div><div className="grid overflow-hidden rounded-xl border border-[var(--border)] bg-[var(--border)] sm:grid-cols-2 lg:grid-cols-5">{kpis.map(([label,value,note,href])=><Link href={href} key={label} className="group bg-[var(--surface)] px-4 py-4 transition hover:bg-[var(--surface-2)]"><div className="flex justify-between"><span className="font-mono text-[8px] font-semibold tracking-[.16em] text-[var(--text-muted)]">{label}</span><span className="opacity-0 text-[var(--accent)] transition group-hover:opacity-100">↗</span></div><div className="mt-2 flex items-end justify-between"><div><div className="text-[28px] font-semibold tracking-[-.05em]">{value}</div><div className="mt-1 text-[8px] text-[var(--text-muted)]">{note}</div></div><Spark/></div></Link>)}</div></section>

  <section className="grid gap-4 py-5 xl:grid-cols-[minmax(0,1.5fr)_minmax(300px,.7fr)]"><div className="nexor-panel overflow-hidden"><div className="flex items-center justify-between border-b border-[var(--border)] px-5 py-4"><div><div className="font-mono text-[8px] font-semibold tracking-[.18em] text-[var(--accent)]">REVENUE INTELLIGENCE</div><div className="mt-1 text-[15px] font-semibold">Pipeline momentum</div></div><span className="rounded-md border border-[var(--border)] px-2 py-1 font-mono text-[7px] text-[var(--text-muted)]">30 DAYS</span></div><div className="p-5"><div className="mb-4 flex justify-between"><div><div className="text-[30px] font-semibold tracking-[-.05em]">{s.won}<span className="ml-2 text-[11px] font-medium text-[var(--text-muted)]">closed</span></div><div className="mt-1 text-[9px] text-[var(--success)]">● Current conversion output</div></div><div className="text-right font-mono text-[7px] text-[var(--text-muted)]">QUALIFIED {q}%</div></div><div className="relative h-[250px] overflow-hidden rounded-lg border border-[var(--border)] bg-[var(--surface-2)]"><div className="absolute inset-0 opacity-50 [background-image:linear-gradient(var(--border)_1px,transparent_1px),linear-gradient(90deg,var(--border)_1px,transparent_1px)] [background-size:25%_25%]"/><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="absolute inset-5 h-[calc(100%-40px)] w-[calc(100%-40px)]"><polyline points="8,82 20,70 32,76 44,57 56,61 68,46 80,51 92,30" fill="none" stroke="currentColor" strokeWidth="1.2" vectorEffect="non-scaling-stroke" className="text-[var(--accent)]"/><line x1="8" y1="88" x2="92" y2="88" stroke="currentColor" strokeOpacity=".15" vectorEffect="non-scaling-stroke"/></svg><div className="absolute inset-x-4 bottom-3 flex justify-between font-mono text-[7px] text-[var(--text-muted)]"><span>01 AUG</span><span>31 AUG</span></div></div></div></div>
   <div className="nexor-panel overflow-hidden"><div className="border-b border-[var(--border)] px-5 py-4"><div className="font-mono text-[8px] font-semibold tracking-[.18em] text-[var(--text-muted)]">CONVERSION ENGINE</div><div className="mt-1 text-[15px] font-semibold">Funnel health</div></div><div className="p-4">{funnel.map(([label,value,pct])=><div key={label} className="border-b border-[var(--border)] py-3 last:border-0"><div className="mb-2 flex justify-between"><span className="text-[9px] font-medium text-[var(--text-secondary)]">{label}</span><span className="font-mono text-[8px] text-[var(--text-muted)]">{value}</span></div><div className="h-1 rounded-full bg-[var(--surface-3)]"><div className="h-full rounded-full bg-[var(--accent)]" style={{width:`${Math.min(100,Math.max(value?5:0,pct))}%`}}/></div></div>)}</div></div>
  </section>

  <section className="grid gap-4 lg:grid-cols-2"><div className="nexor-panel overflow-hidden"><div className="flex items-center justify-between border-b border-[var(--border)] px-5 py-4"><div><div className="font-mono text-[8px] font-semibold tracking-[.18em] text-amber-600 dark:text-amber-300/70">NEEDS ATTENTION</div><div className="mt-1 text-[15px] font-semibold">Operator queue</div></div><span className="rounded-full border border-amber-500/20 bg-amber-500/[.06] px-2 py-1 font-mono text-[7px] text-amber-700 dark:text-amber-300">{s.drafts} OPEN</span></div><div className="divide-y divide-[var(--border)]"><Link href="/dashboard/tools/follow-up-manager" className="group flex gap-4 px-5 py-4 transition hover:bg-[var(--surface-2)]"><span className="mt-1.5 h-2 w-2 rounded-full bg-amber-400"/><div className="flex-1"><div className="text-[11px] font-medium">Outreach approvals are waiting</div><div className="mt-1 text-[9px] text-[var(--text-muted)]">{s.drafts} drafts require review before sending.</div></div><span className="opacity-0 transition group-hover:opacity-100">→</span></Link><Link href="/dashboard/tools/lead-inbox" className="group flex gap-4 px-5 py-4 transition hover:bg-[var(--surface-2)]"><span className="mt-1.5 h-2 w-2 rounded-full bg-[var(--accent)]"/><div className="flex-1"><div className="text-[11px] font-medium">Work qualified opportunities</div><div className="mt-1 text-[9px] text-[var(--text-muted)]">{s.qualified} records are currently sales-ready.</div></div><span className="opacity-0 transition group-hover:opacity-100">→</span></Link><Link href="/dashboard/command" className="group flex gap-4 px-5 py-4 transition hover:bg-[var(--surface-2)]"><span className="mt-1.5 h-2 w-2 rounded-full bg-emerald-400"/><div className="flex-1"><div className="text-[11px] font-medium">Run today's operating brief</div><div className="mt-1 text-[9px] text-[var(--text-muted)]">Surface movement, anomalies and next-best actions.</div></div><span className="opacity-0 transition group-hover:opacity-100">→</span></Link></div></div>
  <div className="nexor-panel overflow-hidden"><div className="border-b border-[var(--border)] px-5 py-4"><div className="font-mono text-[8px] font-semibold tracking-[.18em] text-[var(--accent)]">NEXOR INTELLIGENCE</div><div className="mt-1 text-[15px] font-semibold">Executive brief</div></div><div className="space-y-3 p-5"><div className="rounded-lg border border-[var(--border)] bg-[var(--surface-2)] p-4"><div className="font-mono text-[8px] text-[var(--text-muted)]">OBSERVATION</div><p className="mt-2 text-[11px] leading-5 text-[var(--text-secondary)]">The operation contains <strong className="text-[var(--text)]">{s.qualified} qualified leads</strong> and <strong className="text-[var(--text)]">{s.meetings} meetings</strong>.</p></div><div className="rounded-lg border border-[var(--accent)]/20 bg-[var(--accent-soft)] p-4"><div className="font-mono text-[8px] text-[var(--accent)]">RECOMMENDED ACTION</div><p className="mt-2 text-[11px] leading-5 text-[var(--text-secondary)]">Clear approval work first, then work the highest-intent qualified leads before increasing outbound volume.</p><Link href="/dashboard/tools/follow-up-manager" className="mt-3 inline-flex text-[9px] font-semibold text-[var(--accent)]">Review priorities →</Link></div></div></div></section>

  <section className="grid gap-4 py-5 xl:grid-cols-[1.25fr_.75fr]"><div className="nexor-panel overflow-hidden"><div className="flex items-center justify-between border-b border-[var(--border)] px-5 py-4"><div><div className="font-mono text-[8px] font-semibold tracking-[.18em] text-[var(--text-muted)]">ACQUISITION CONTROL</div><div className="mt-1 text-[15px] font-semibold">Campaign operations</div></div><Link href="/dashboard/command" className="text-[9px] font-semibold text-[var(--accent)]">View all →</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead><tr className="border-b border-[var(--border)] font-mono text-[7px] tracking-[.12em] text-[var(--text-muted)]"><th className="px-5 py-3 font-medium">CHANNEL</th><th className="px-3 py-3 font-medium">RUNNING</th><th className="px-3 py-3 font-medium">LEADS</th><th className="px-3 py-3 font-medium">SENT</th><th className="px-3 py-3 font-medium">STATE</th></tr></thead><tbody><tr className="transition hover:bg-[var(--surface-2)]"><td className="px-5 py-4 text-[10px] font-medium">Paid + outbound acquisition</td><td className="px-3 py-4 text-[10px]">{s.campaigns}</td><td className="px-3 py-4 text-[10px]">{s.leads}</td><td className="px-3 py-4 text-[10px]">{s.sent}</td><td className="px-3 py-4"><span className="rounded-full bg-emerald-500/[.08] px-2 py-1 font-mono text-[7px] text-emerald-600 dark:text-emerald-300">LIVE</span></td></tr></tbody></table></div></div><div className="nexor-panel overflow-hidden"><div className="border-b border-[var(--border)] px-5 py-4"><div className="font-mono text-[8px] font-semibold tracking-[.18em] text-[var(--text-muted)]">LIVE ACTIVITY</div><div className="mt-1 text-[15px] font-semibold">Operating stream</div></div><div className="divide-y divide-[var(--border)]">{[['OUTREACH',`${s.sent} messages sent`],['CRM',`${s.qualified} qualified records`],['SALES',`${s.meetings} meetings booked`],['SYSTEM',s.db?'Database healthy':'Database requires configuration']].map(([a,b])=><div key={a} className="flex items-center gap-3 px-5 py-3.5"><span className="h-1.5 w-1.5 rounded-full bg-[var(--accent)]"/><div className="flex-1 text-[10px] font-medium">{b}<div className="mt-0.5 font-mono text-[7px] text-[var(--text-muted)]">{a}</div></div><span className="font-mono text-[7px] text-[var(--text-muted)]">NOW</span></div>)}</div></div></section>

  <section className="relative overflow-hidden rounded-xl border border-[var(--border-strong)] bg-[var(--surface)] p-5 shadow-[var(--shadow)]"><div className="relative flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="font-mono text-[8px] font-semibold tracking-[.18em] text-[var(--accent)]">NEXOR COMMAND</div><div className="mt-1 text-[16px] font-semibold">What should Nexor do next?</div><div className="mt-1 text-[10px] text-[var(--text-muted)]">Search the OS, inspect performance, research opportunities or launch an approved workflow.</div></div><Link href="/dashboard/command" className="inline-flex shrink-0 items-center justify-center rounded-lg bg-[var(--text)] px-5 py-3 text-[10px] font-semibold text-[var(--bg)] transition hover:-translate-y-px">⌘ Open command center →</Link></div></section>

  <section className="pt-6"><div className="mb-3 font-mono text-[8px] font-semibold tracking-[.18em] text-[var(--text-muted)]">QUICK ACCESS</div><div className="grid gap-2 sm:grid-cols-3 lg:grid-cols-4">{nav.map(([label,href])=><Link key={label} href={href} className="group rounded-lg border border-[var(--border)] bg-[var(--surface)] px-3 py-3 transition hover:border-[var(--border-strong)] hover:bg-[var(--surface-2)]"><span className="text-[10px] font-medium">{label}</span><span className="float-right text-[var(--text-muted)] opacity-0 transition group-hover:opacity-100">↗</span></Link>)}</div></section>
 </main></DashboardLayout>;
}
