'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';

type Lead={id:string;businessName:string;whatsapp:string|null};
type Item={id:string;message:string;status:string;scheduledAt:string|null;sentAt?:string|null;error?:string|null;providerMessageId?:string|null;lead:Lead};
type Provider={configured:boolean;mode:string;openwaConfigured:boolean;templateConfigured:boolean;templateLanguage:string;automationReady?:boolean};
type Data={provider:Provider;stats:{drafts:number;approved:number;scheduled:number;sent:number;failed:number;failedLast24h:number;replies:number;notContactable:number;whatsappHold?:number;rejected:number};drafts:Item[];approved:Item[];scheduled:Item[];recentFailed:Array<{id:string;businessName:string;reason:string;updatedAt:string;isRecent:boolean}>};

type Tab='QUEUE'|'SENT'|'FAILED'|'BLOCKED';

export default function WhatsAppAutomationPage(){
 const [data,setData]=useState<Data|null>(null);const [history,setHistory]=useState<Item[]>([]);const [tab,setTab]=useState<Tab>('QUEUE');const [loading,setLoading]=useState(true);const [running,setRunning]=useState(false);const [message,setMessage]=useState('');
 const load=useCallback(async()=>{try{const [a,o]=await Promise.all([fetch('/api/whatsapp/automation',{cache:'no-store'}),fetch('/api/outreach',{cache:'no-store'})]);const aj=await a.json();const oj=await o.json();if(!a.ok||!aj.success)throw new Error(aj.error||'WhatsApp automation unavailable');setData(aj);if(oj.success)setHistory((oj.drafts||[]).filter((x:Item)=>x.channel==='WHATSAPP'));setMessage('')}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();const t=window.setInterval(()=>void load(),10000);return()=>window.clearInterval(t)},[load]);
 async function run(action:string){setRunning(true);setMessage('');try{const r=await fetch('/api/whatsapp/automation',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,limit:10})});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error||'Automation action failed');setMessage(action==='generate'?`Checked ${j.considered??0} leads · created ${j.created??0} · rejected ${j.rejected?.length??0}.`:`Sent ${j.sent??0} · failed ${j.failed??0}.`);await load()}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setRunning(false)}}
 const sent=useMemo(()=>history.filter(x=>x.status==='SENT').slice(0,50),[history]);
 const failed=useMemo(()=>history.filter(x=>x.status==='FAILED').slice(0,50),[history]);
 const queue=useMemo(()=>[...(data?.approved||[]),...(data?.scheduled||[]),...(data?.drafts||[])], [data]);
 const blocked=useMemo(()=>history.filter(x=>['CANCELLED'].includes(x.status)).slice(0,50),[history]);
 const provider=data?.provider;const ready=Boolean(provider?.automationReady);const openwa=Boolean(provider?.openwaConfigured);
 return <main className="mx-auto w-full max-w-6xl space-y-4 px-0 py-0 sm:space-y-5">
  <section className="nexor-panel overflow-hidden p-4 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="font-mono text-[7px] tracking-[.18em] text-[var(--accent)]">SALES · WHATSAPP OS</div><h1 className="mt-1 text-2xl font-semibold tracking-[-.03em]">WhatsApp Control Room</h1><p className="mt-1.5 max-w-2xl text-[9px] leading-5 text-[var(--text-secondary)]">One place for drafts, approved queue, sent messages and failures. The UI never calls an approved message “sent” until the provider confirms it.</p></div><div className={`rounded-full px-3 py-2 font-mono text-[8px] font-bold ${ready?'bg-emerald-500/10 text-emerald-500':'bg-amber-500/10 text-amber-500'}`}>{ready?'● PROVIDER READY':'● PROVIDER CHECK'}</div></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><div className="nx-mini-stat"><span>PROVIDER</span><strong>{openwa?'OpenWA':'Meta'}</strong></div><div className="nx-mini-stat"><span>QUEUE</span><strong>{data?.stats.approved??0}</strong></div><div className="nx-mini-stat"><span>SENT</span><strong>{data?.stats.sent??0}</strong></div><div className="nx-mini-stat"><span>FAILED</span><strong>{data?.stats.failed??0}</strong></div></div>{!openwa&&<div className="mt-3 nx-feedback">Meta first-contact sending requires an approved template. OpenWA is the active path when its three production variables are configured.</div>}{message&&<div className="mt-3 nx-feedback">{message}</div>}</section>
  <section className="nexor-panel p-3 sm:p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div className="nx-tabbar w-full sm:w-auto">{(['QUEUE','SENT','FAILED','BLOCKED'] as Tab[]).map(x=><button key={x} className={`nx-tab ${tab===x?'nx-tab-active':''}`} onClick={()=>setTab(x)}>{x==='QUEUE'?`Queue ${queue.length}`:x==='SENT'?`Sent ${sent.length}`:x==='FAILED'?`Failed ${failed.length}`:`Blocked ${blocked.length}`}</button>)}</div><button onClick={()=>void run('generate')} disabled={running||loading} className="nx-primary-action sm:!mt-0 sm:w-auto">{running?'RUNNING…':'RUN AUTOPILOT'}</button></div></section>
  <section className="nexor-panel overflow-hidden">
   <div className="nx-section-head"><div><div className="text-[11px] font-semibold">{tab==='QUEUE'?'Live send queue':tab==='SENT'?'Provider-confirmed delivery':tab==='FAILED'?'Failed attempts':'Other outreach states'}</div><div className="mt-1 text-[8px] text-[var(--text-muted)]">Auto-refreshing every 10 seconds.</div></div><span className="nx-live-dot">LIVE</span></div>
   <div className="divide-y divide-[var(--border)]">
    {(tab==='QUEUE'?queue:tab==='SENT'?sent:tab==='FAILED'?failed:blocked).map(item=><article key={item.id} className="nx-outreach-row"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><strong className="break-words text-[10px]">{item.lead?.businessName||'Unknown lead'}</strong><span className="nx-status nx-status-muted">WHATSAPP</span><span className={`nx-status ${item.status==='SENT'?'nx-status-ok':item.status==='FAILED'?'nx-status-danger':item.status==='APPROVED'?'nx-status-ai':'nx-status-warn'}`}>{item.status}</span></div><div className="mt-1 font-mono text-[8px] text-[var(--text-muted)]">{item.lead?.whatsapp||'No number'}</div><details className="nx-message-details mt-2"><summary>View message</summary><div className="mt-2 whitespace-pre-wrap break-words rounded-lg bg-[var(--surface-2)] p-3 text-[9px] leading-5 text-[var(--text-secondary)]">{item.message}</div></details>{item.error&&<div className="mt-2 rounded-lg border border-red-500/20 bg-red-500/5 p-2 text-[8px] leading-4 text-red-400">{item.error}</div>}{item.status==='SENT'&&<div className="mt-2 font-mono text-[7px] text-emerald-500">Provider ID: {item.providerMessageId||'confirmed'}</div>}</div><div className="shrink-0 text-left text-[8px] text-[var(--text-muted)] sm:text-right">{item.sentAt?`Sent ${new Date(item.sentAt).toLocaleString()}`:item.scheduledAt?`Due ${new Date(item.scheduledAt).toLocaleString()}`:''}</div></article>)}
    {!(tab==='QUEUE'?queue:tab==='SENT'?sent:tab==='FAILED'?failed:blocked).length&&<div className="p-10 text-center text-[9px] text-[var(--text-muted)]">{tab==='SENT'?'No provider-confirmed WhatsApp messages yet.':tab==='FAILED'?'No failed WhatsApp records.':'Nothing in this view.'}</div>}
   </div>
  </section>
  <section className="nexor-panel p-4"><div className="text-[10px] font-semibold">Why a message may not send</div><div className="mt-2 grid gap-2 sm:grid-cols-3"><div className="rounded-lg bg-[var(--surface-2)] p-3 text-[8px] leading-4 text-[var(--text-muted)]">1. Lead must be an eligible international business lead.</div><div className="rounded-lg bg-[var(--surface-2)] p-3 text-[8px] leading-4 text-[var(--text-muted)]">2. WhatsApp opt-in must be recorded before automated first contact.</div><div className="rounded-lg bg-[var(--surface-2)] p-3 text-[8px] leading-4 text-[var(--text-muted)]">3. Provider must confirm delivery; otherwise Nexor records the real failure.</div></div></section>
 </main>;
}
